const {
  applyInvokeSearchPostUpstreamFlow: applyInvokeSearchPostUpstreamFlowBase,
} = require('./catalog/postUpstreamFallback');
const {
  finalizeInvokeSuccessResponse: finalizeInvokeSuccessResponseBase,
} = require('./finalizeInvokeSuccessResponse');
const {
  buildSearchTrace: buildSearchTraceBase,
} = require('./catalog/searchTrace');

function attachInvokeRouteDebugMetadata({
  operation,
  upstreamData,
  routeDebugEnabled,
  creatorCacheRouteDebug,
  crossMerchantCacheRouteDebug,
} = {}) {
  if (
    operation !== 'find_products_multi' ||
    !routeDebugEnabled ||
    (!creatorCacheRouteDebug && !crossMerchantCacheRouteDebug)
  ) {
    return upstreamData;
  }

  return {
    ...upstreamData,
    metadata: {
      ...(upstreamData?.metadata || {}),
      route_debug: {
        ...((upstreamData?.metadata && upstreamData.metadata.route_debug) || {}),
        ...(creatorCacheRouteDebug ? { creator_cache: creatorCacheRouteDebug } : {}),
        ...(crossMerchantCacheRouteDebug ? { cross_merchant_cache: crossMerchantCacheRouteDebug } : {}),
      },
    },
  };
}

async function finalizeInvokeResponseFlow({
  operation,
  upstreamData,
  responseStatus,
  payload,
  queryParams,
  metadata,
  rawUserQuery,
  effectiveIntent,
  traceQueryClass,
  checkoutToken,
  resolverFirstResult,
  resolverTimeoutMs,
  shouldAttemptResolverFirst,
  isProxySearchRoute,
  proxyRouteFallbackStrategy,
  auroraFallbackOverrides,
  auroraExternalSeedEnabled,
  auroraExternalSeedStrategy,
  auroraUpstreamBase,
  fpmLatencyGuardApplied,
  fpmSkippedGatesDueToBudget,
  addFpmGateTrace,
  getFpmRemainingBudgetMs,
  searchLimitMax,
  findProductsMultiSecondStageExpansionMode,
  fpmGateSimplifyV1,
  fpmLatencyGuardSecondStageMinRemainingMs,
  searchExternalHardRulePrune,
  detectBrandEntities,
  extractSearchQueryText,
  extractSearchAnchorTokens,
  isLookupStyleSearchQuery,
  normalizeAgentProductsListResponse,
  countUsableSearchProducts,
  shouldFallbackProxySearch,
  isProxySearchFallbackRelevant,
  evaluateCacheQualityGate,
  computePrimaryQualityScore,
  isExternalSeedProduct,
  detectAuroraExternalSeedMonoculture,
  hasFragranceQuerySignal,
  getSecondaryFallbackSkipReason,
  shouldAllowResolverFallback,
  shouldAllowSecondaryFallback,
  shouldAllowInvokeFallback,
  buildFindProductsMultiContext,
  axios,
  url,
  buildQueryString,
  axiosConfig,
  buildSearchProductKey,
  isSupplementCandidateRelevant,
  queryResolveSearchFallback,
  queryFindProductsMultiFallback,
  getFallbackAdoptUsableThreshold,
  buildProxySearchSoftFallbackResponse,
  withProxySearchFallbackMetadata,
  normalizeAgentSource,
  requestBody,
  resolvedOfferId,
  resolvedMerchantId,
  gatewayRequestId,
  productDetailCacheKey,
  productDetailCacheMeta,
  productDetailDebug,
  productDetailBypassCache,
  normalizeAgentProductDetailResponse,
  effectivePayload,
  policyMetadata,
  creatorId,
  hasDatabase,
  now,
  creatorCacheRouteDebug,
  crossMerchantCacheRouteDebug,
  invokeStartedAtMs,
  traceRewriteGate,
  traceAssociationPlan,
  traceFlagsSnapshot,
  traceAmbiguityScorePre,
  findProductsExpansionMeta,
  fpmGateTrace,
  routeDebugEnabled,
  searchStrictEmptyEnabled,
  fpmClarifyNeverEmpty,
  searchRelevanceDebugEnabled,
  defaultFindProductsMultiExpansionMode,
  isKnownLookupAliasQuery,
  applyFindProductsMultiPolicy,
  buildPetFallbackQuery,
  searchCreatorSellableFromCache,
  maybeRerankFindProductsMultiResponse,
  withSearchDiagnostics,
  buildSearchRouteHealth,
  buildSearchTrace = buildSearchTraceBase,
  buildSearchRelevanceDebug,
  applyInvokeSearchPostUpstreamFlow = applyInvokeSearchPostUpstreamFlowBase,
  finalizeInvokeSuccessResponse = finalizeInvokeSuccessResponseBase,
  logger,
} = {}) {
  let finalizedUpstreamData = attachInvokeRouteDebugMetadata({
    operation,
    upstreamData,
    routeDebugEnabled,
    creatorCacheRouteDebug,
    crossMerchantCacheRouteDebug,
  });

  if (operation === 'find_products' || operation === 'find_products_multi') {
    finalizedUpstreamData = normalizeAgentProductsListResponse(finalizedUpstreamData, {
      limit: queryParams?.limit,
      offset: queryParams?.offset,
    });
  }

  if (operation === 'find_products' || operation === 'find_products_multi') {
    const postUpstreamSearchFlow = await applyInvokeSearchPostUpstreamFlow({
      operation,
      upstreamData: finalizedUpstreamData,
      responseStatus,
      payload,
      queryParams,
      metadata,
      rawUserQuery,
      effectiveIntent,
      traceQueryClass,
      checkoutToken,
      resolverFirstResult,
      resolverTimeoutMs,
      shouldAttemptResolverFirst,
      isProxySearchRoute,
      proxyRouteFallbackStrategy,
      auroraFallbackOverrides,
      auroraExternalSeedEnabled,
      auroraExternalSeedStrategy,
      auroraUpstreamBase,
      fpmLatencyGuardApplied,
      fpmSkippedGatesDueToBudget,
      addFpmGateTrace,
      getFpmRemainingBudgetMs,
      searchLimitMax,
      findProductsMultiSecondStageExpansionMode,
      fpmGateSimplifyV1,
      fpmLatencyGuardSecondStageMinRemainingMs,
      searchExternalHardRulePrune,
      detectBrandEntities,
      extractSearchQueryText,
      extractSearchAnchorTokens,
      isLookupStyleSearchQuery,
      normalizeAgentProductsListResponse,
      countUsableSearchProducts,
      shouldFallbackProxySearch,
      isProxySearchFallbackRelevant,
      evaluateCacheQualityGate,
      computePrimaryQualityScore,
      isExternalSeedProduct,
      detectAuroraExternalSeedMonoculture,
      hasFragranceQuerySignal,
      getSecondaryFallbackSkipReason,
      shouldAllowResolverFallback,
      shouldAllowSecondaryFallback,
      shouldAllowInvokeFallback,
      buildFindProductsMultiContext,
      axios,
      url,
      buildQueryString,
      axiosConfig,
      buildSearchProductKey,
      isSupplementCandidateRelevant,
      queryResolveSearchFallback,
      queryFindProductsMultiFallback,
      getFallbackAdoptUsableThreshold,
      buildProxySearchSoftFallbackResponse,
      withProxySearchFallbackMetadata,
      normalizeAgentSource,
      logger,
    });
    finalizedUpstreamData = postUpstreamSearchFlow.upstreamData;
    proxyRouteFallbackStrategy = postUpstreamSearchFlow.proxyRouteFallbackStrategy;
    fpmLatencyGuardApplied = postUpstreamSearchFlow.fpmLatencyGuardApplied;
    fpmSkippedGatesDueToBudget = postUpstreamSearchFlow.fpmSkippedGatesDueToBudget;
  }

  const successFinalize = await finalizeInvokeSuccessResponse({
    operation,
    upstreamData: finalizedUpstreamData,
    responseStatus,
    requestBody,
    resolvedOfferId,
    resolvedMerchantId,
    gatewayRequestId,
    payload,
    productDetailCacheKey,
    productDetailCacheMeta,
    productDetailDebug,
    productDetailBypassCache,
    normalizeAgentProductDetailResponse,
    queryParams,
    metadata,
    rawUserQuery,
    effectiveIntent,
    effectivePayload,
    policyMetadata,
    creatorId,
    hasDatabase,
    now,
    crossMerchantCacheRouteDebug,
    shouldAttemptResolverFirst,
    resolverFirstResult,
    invokeStartedAtMs,
    traceQueryClass,
    traceRewriteGate,
    traceAssociationPlan,
    traceFlagsSnapshot,
    traceAmbiguityScorePre,
    proxyRouteFallbackStrategy,
    findProductsExpansionMeta,
    fpmGateTrace,
    fpmSkippedGatesDueToBudget,
    fpmLatencyGuardApplied,
    searchLimitMax,
    routeDebugEnabled,
    searchStrictEmptyEnabled,
    fpmClarifyNeverEmpty,
    searchRelevanceDebugEnabled,
    defaultFindProductsMultiExpansionMode,
    extractSearchQueryText,
    extractSearchAnchorTokens,
    isLookupStyleSearchQuery,
    isKnownLookupAliasQuery,
    applyFindProductsMultiPolicy,
    buildPetFallbackQuery,
    searchCreatorSellableFromCache,
    maybeRerankFindProductsMultiResponse,
    withSearchDiagnostics,
    buildSearchRouteHealth,
    buildSearchTrace,
    buildSearchRelevanceDebug,
    logger,
  });

  return {
    body: successFinalize.body,
    upstreamData: successFinalize.upstreamData,
    checkoutRuntime: successFinalize.checkoutRuntime || null,
    proxyRouteFallbackStrategy,
    fpmLatencyGuardApplied,
    fpmSkippedGatesDueToBudget,
  };
}

module.exports = {
  attachInvokeRouteDebugMetadata,
  finalizeInvokeResponseFlow,
};
