# Copy this file to: .github/workflows/aurora-bff-release-gate.yml
name: Aurora BFF Release Gate

on:
  pull_request:
    paths:
      - "src/**"
      - "scripts/**"
      - "tests/**"
      - "docs/**"
      - "Makefile"
      - "package.json"
      - "package-lock.json"
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      base_url:
        description: "Base URL for runtime smoke (default: production)"
        required: false
        default: "https://pivota-agent-production.up.railway.app"
      wait_for_commit:
        description: "Wait for deployed X-Service-Commit to match this workflow's GITHUB_SHA"
        type: boolean
        required: false
        default: true

concurrency:
  group: aurora-bff-release-gate
  cancel-in-progress: true

jobs:
  unit:
    name: Unit + Contract Gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Reco guardrail gate (fail-fast)
        shell: bash
        run: |
          set -euo pipefail
          make reco-guardrail-eval

      - name: Aurora BFF unit tests (offline)
        run: npm run test:aurora-bff:unit

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pytest
        run: python -m pip install --upgrade pip pytest

      - name: E2E contract tests (offline)
        run: make test

      - name: Generate RELEASE_GATE.md
        run: make release-gate

      - name: Upload RELEASE_GATE.md
        uses: actions/upload-artifact@v4
        with:
          name: RELEASE_GATE
          path: RELEASE_GATE.md
          if-no-files-found: error

  runtime_smoke:
    name: Runtime Smoke (deployed)
    runs-on: ubuntu-latest
    needs: [unit]
    if: github.event_name != 'pull_request'
    env:
      BASE_URL: ${{ inputs.base_url || vars.AURORA_BFF_BASE_URL || 'https://pivota-agent-production.up.railway.app' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Wait for deployment to match commit (best-effort)
        if: github.event_name != 'workflow_dispatch' || inputs.wait_for_commit == true
        shell: bash
        run: |
          set -euo pipefail
          target="${GITHUB_SHA:0:12}"
          echo "BASE_URL=$BASE_URL"
          echo "target_commit=$target"

          deployed=""
          for i in {1..80}; do
            deployed="$(curl -sSI "$BASE_URL/v1/session/bootstrap" | tr -d '\r' | awk -F': ' 'tolower($1)=="x-service-commit" {print $2}' | head -n 1 || true)"
            echo "$i deployed_commit=${deployed:-missing}"
            if [[ -n "${deployed:-}" && "$deployed" == "$target" ]]; then
              echo "Deployment matches."
              exit 0
            fi
            sleep 10
          done

          echo "Timed out waiting for deployment to match commit. deployed=${deployed:-missing} target=$target"
          exit 1

      - name: Runtime smoke (hits BASE_URL)
        shell: bash
        run: |
          set -euo pipefail
          BASE="$BASE_URL" bash scripts/smoke_aurora_bff_runtime.sh
