const {
  buildSearchRouteHealth,
} = require('../../src/commerce/catalog/searchRouteHealth');

describe('buildSearchRouteHealth', () => {
  test('applies stable defaults', () => {
    expect(buildSearchRouteHealth({})).toEqual(
      expect.objectContaining({
        orchestrator_path: 'external_invoke_route',
        decision_node: 'unknown',
        primary_path_used: 'unknown',
        primary_latency_ms: 0,
        fallback_triggered: false,
        fallback_reason: null,
        query_semantic_class: 'default',
        external_seed_skip_reason: null,
        external_seed_cache_hit: false,
        ambiguity_score_pre: 0,
        ambiguity_score_post: 0,
        primary_quality_score: 0,
        clarify_triggered: false,
        degrade_flags: null,
      }),
    );
  });

  test('normalizes numeric ranges and derives external seed cache hit from skip reason', () => {
    const result = buildSearchRouteHealth({
      orchestratorPath: 'local_proxy',
      decisionNode: 'fallback_after_primary',
      primaryPathUsed: 'agent_search_global',
      primaryLatencyMs: -12,
      fallbackTriggered: 1,
      fallbackReason: 'resolver_miss',
      querySemanticClass: 'lookup',
      domainFilterDroppedExternal: '7',
      semanticRetryApplied: true,
      semanticRetryActualAttempted: true,
      semanticRetryQuery: 'ipsa toner',
      semanticRetryHits: '3',
      externalSeedSkipReason: 'cache_hit',
      externalSeedRowsFetched: '4',
      externalSeedRowsBuilt: 2,
      externalSeedBrandStrictRows: 1,
      externalSeedBrandRelevantRows: 5,
      externalSeedBroadFallbackUsed: true,
      externalSeedBroadScopeRows: '6',
      internalRawCount: 9,
      externalRawCount: 10,
      mergedPreLimitCount: 12,
      primaryQualityGatePassed: false,
      primaryQualityScore: 1.8,
      lowQualityNonemptyDetected: true,
      supplementAttempted: true,
      supplementSkipReason: 'query_unchanged',
      retryAttemptCount: 2,
      fallbackAttemptCount: 3,
      selectedFallbackAttempt: 2,
      finalReturnedCount: 8,
      ambiguityScorePre: -0.4,
      ambiguityScorePost: 1.7,
      clarifyTriggered: true,
      degradeFlags: {
        vector_skipped: 1,
        behavior_skipped: 0,
        nlu_degraded: true,
      },
    });

    expect(result).toEqual(
      expect.objectContaining({
        orchestrator_path: 'local_proxy',
        decision_node: 'fallback_after_primary',
        primary_path_used: 'agent_search_global',
        primary_latency_ms: 0,
        fallback_triggered: true,
        fallback_reason: 'resolver_miss',
        query_semantic_class: 'lookup',
        domain_filter_dropped_external: 7,
        semantic_retry_applied: true,
        semantic_retry_actual_attempted: true,
        semantic_retry_query: 'ipsa toner',
        semantic_retry_hits: 3,
        external_seed_skip_reason: 'cache_hit',
        external_seed_cache_hit: true,
        external_seed_rows_fetched: 4,
        external_seed_rows_built: 2,
        external_seed_brand_strict_rows: 1,
        external_seed_brand_relevant_rows: 5,
        external_seed_broad_fallback_used: true,
        external_seed_broad_scope_rows: 6,
        internal_raw_count: 9,
        external_raw_count: 10,
        merged_pre_limit_count: 12,
        primary_quality_gate_passed: false,
        primary_quality_score: 1,
        low_quality_nonempty_detected: true,
        supplement_attempted: true,
        supplement_skip_reason: 'query_unchanged',
        retry_attempt_count: 2,
        fallback_attempt_count: 3,
        selected_fallback_attempt: 2,
        final_returned_count: 8,
        ambiguity_score_pre: 0,
        ambiguity_score_post: 1,
        clarify_triggered: true,
        degrade_flags: {
          vector_skipped: true,
          behavior_skipped: false,
          nlu_degraded: true,
        },
      }),
    );
  });
});
