const { createChatRecoEntryRuntime } = require('./chatRecoEntryRuntime');
const { createChatRecoPreludeRuntime } = require('./chatRecoPreludeRuntime');
const { createChatRecoHandoffRuntime } = require('./chatRecoHandoffRuntime');
const { createChatRecoResponseRuntime } = require('./chatRecoResponseRuntime');
const { createChatRecoResolveRuntime } = require('./chatRecoResolveRuntime');
const { createChatRecoArtifactRuntime } = require('./chatRecoArtifactRuntime');
const { createChatRoutineGateRuntime } = require('./chatRoutineGateRuntime');
const { createChatRecommendationRuntime } = require('./chatRecommendationRuntime');
const { createChatRecommendationFlowRuntime } = require('./chatRecommendationFlowRuntime');
const { createChatRoutineRecoRuntime } = require('./chatRoutineRecoRuntime');

function createChatRecommendationRuntimeBundle(options = {}) {
  const {
    logger,
    mergeIngredientRecoContextValue,
    pickFirstTrimmed,
    normalizeIngredientCandidateList,
    extractIngredientLookupTargetFromText,
    profileCompleteness,
    evaluateSafetyBoundary,
    buildConfidenceNoticeCardPayload,
    recordAuroraSkinFlowMetric,
    recordAuroraRecoEntrySource,
    looksLikeRoutineRequest,
    looksLikeSuitabilityRequest,
    looksLikeRecommendationRequest,
    looksLikeCompatibilityOrConflictQuestion,
    looksLikeWeatherOrEnvironmentQuestion,
    isBudgetClarificationAction,
    isBareBudgetSelectionMessage,
    buildIngredientPlanCard,
    buildRulesOnlyRoutineExpertFromContext,
    appendLatestArtifactToSessionPatch,
    appendLatestRecoContextToSessionPatch,
    buildRecoLlmTraceRef,
    normalizeRecoSourceDetail,
    generateRoutineReco,
    AURORA_BFF_CHAT_ROUTINE_V2_ENABLED,
    withTimeout,
    AURORA_BFF_CHAT_ROUTINE_BUDGET_MS,
    buildBudgetOptimizationEntryChip,
    stateChangeAllowed,
    stripInternalRefsDeep,
    isBudgetOptimizationEntryAction,
    buildBudgetGatePrompt,
    buildBudgetGateChips,
    normalizeBudgetHint,
    upsertProfileForIdentity,
    isPlainObject,
    applyRecoWarningVisibilityContract,
    RECO_MAIN_PROMPT_TEMPLATE_ID,
    buildRouteAwareAssistantText,
    addEmotionalPreambleToAssistantText,
    deriveRecoEmptyReason,
    recordAuroraRecoKbWrite,
    saveRecoRun,
    AURORA_PRODUCT_MATCHER_ENABLED,
    DIAG_PRODUCT_CATALOG_PATH,
    AURORA_BFF_CHAT_RECO_BUDGET_MS,
    generateProductRecommendations,
    normalizeRecoFailureClass,
    classifyRecoUpstreamFailureCode,
    isTransientRecoUpstreamFailureCode,
    recordAuroraRecoLlmCall,
    applyIngredientRecoConstraint,
    mergeFieldMissing,
    ingredient_query_normalize,
    setImmediate,
    summarizeProfileForContext,
    buildIngredientPlan,
    buildProductRecommendationsBundle,
    toLegacyRecommendationsPayload,
    extractLatestArtifactIdFromSession,
    getLatestDiagnosisArtifact,
    hasUsableArtifactForRecommendations,
    AURORA_CHAT_NONBLOCKING_GATE_V1_ENABLED,
    looksLikeLowRiskSkincareTask,
    buildRecoEntryChips,
    getIngredientPlanByArtifactId,
    looksLikeIngredientScienceIntent,
    saveIngredientPlan,
    AURORA_INGREDIENT_PLAN_ENABLED,
    chatProfileContinuationRuntime,
  } = options;

  const chatRecoPreludeRuntime = createChatRecoPreludeRuntime({
    logger,
    mergeIngredientRecoContextValue,
    pickFirstTrimmed,
    normalizeIngredientCandidateList,
    extractIngredientLookupTargetFromText,
    profileCompleteness,
    evaluateSafetyBoundary,
    buildConfidenceNoticeCardPayload,
    recordAuroraSkinFlowMetric,
    recordAuroraRecoEntrySource,
  });
  const chatRecoEntryRuntime = createChatRecoEntryRuntime({
    looksLikeRoutineRequest,
    looksLikeSuitabilityRequest,
    looksLikeRecommendationRequest,
    looksLikeCompatibilityOrConflictQuestion,
    looksLikeWeatherOrEnvironmentQuestion,
    isBudgetClarificationAction,
    isBareBudgetSelectionMessage,
  });
  const chatRecoHandoffRuntime = createChatRecoHandoffRuntime({
    buildConfidenceNoticeCardPayload,
    buildIngredientPlanCard,
    buildRulesOnlyRoutineExpertFromContext,
    appendLatestArtifactToSessionPatch,
    appendLatestRecoContextToSessionPatch,
    buildRecoLlmTraceRef,
    normalizeRecoSourceDetail,
  });
  const chatRoutineRecoRuntime = createChatRoutineRecoRuntime({
    logger,
    generateRoutineReco,
    AURORA_BFF_CHAT_ROUTINE_V2_ENABLED,
    withTimeout,
    AURORA_BFF_CHAT_ROUTINE_BUDGET_MS,
    buildBudgetOptimizationEntryChip,
    stateChangeAllowed,
    stripInternalRefsDeep,
    recordAuroraSkinFlowMetric,
    chatRecoHandoffRuntime,
  });
  const chatRoutineGateRuntime = createChatRoutineGateRuntime({
    logger,
    isBudgetOptimizationEntryAction,
    looksLikeSuitabilityRequest,
    looksLikeCompatibilityOrConflictQuestion,
    looksLikeRecommendationRequest,
    looksLikeRoutineRequest,
    looksLikeWeatherOrEnvironmentQuestion,
    buildBudgetGatePrompt,
    buildBudgetGateChips,
    normalizeBudgetHint,
    upsertProfileForIdentity,
    stateChangeAllowed,
    chatRoutineRecoRuntime,
  });
  const chatRecoResponseRuntime = createChatRecoResponseRuntime({
    logger,
    isPlainObject,
    pickFirstTrimmed,
    stateChangeAllowed,
    applyRecoWarningVisibilityContract,
    RECO_MAIN_PROMPT_TEMPLATE_ID,
    buildRecoLlmTraceRef,
    buildRouteAwareAssistantText,
    addEmotionalPreambleToAssistantText,
    stripInternalRefsDeep,
    buildIngredientPlanCard,
    appendLatestArtifactToSessionPatch,
    appendLatestRecoContextToSessionPatch,
    deriveRecoEmptyReason,
    recordAuroraRecoKbWrite,
    saveRecoRun,
    recordAuroraSkinFlowMetric,
    normalizeRecoSourceDetail,
  });
  const chatRecoResolveRuntime = createChatRecoResolveRuntime({
    logger,
    isPlainObject,
    AURORA_PRODUCT_MATCHER_ENABLED,
    DIAG_PRODUCT_CATALOG_PATH,
    AURORA_BFF_CHAT_RECO_BUDGET_MS,
    withTimeout,
    generateProductRecommendations,
    normalizeRecoFailureClass,
    classifyRecoUpstreamFailureCode,
    isTransientRecoUpstreamFailureCode,
    recordAuroraRecoLlmCall,
    applyIngredientRecoConstraint,
    mergeFieldMissing,
    ingredient_query_normalize,
    setImmediate,
    summarizeProfileForContext,
    buildIngredientPlan,
    buildProductRecommendationsBundle,
    toLegacyRecommendationsPayload,
    recordAuroraSkinFlowMetric,
    chatRecoHandoffRuntime,
    chatRecoResponseRuntime,
  });
  const chatRecoArtifactRuntime = createChatRecoArtifactRuntime({
    logger,
    extractLatestArtifactIdFromSession,
    getLatestDiagnosisArtifact,
    hasUsableArtifactForRecommendations,
    AURORA_CHAT_NONBLOCKING_GATE_V1_ENABLED,
    looksLikeLowRiskSkincareTask,
    AURORA_PRODUCT_MATCHER_ENABLED,
    buildRecoEntryChips,
    getIngredientPlanByArtifactId,
    buildIngredientPlan,
    saveIngredientPlan,
    AURORA_INGREDIENT_PLAN_ENABLED,
    recordAuroraSkinFlowMetric,
  });
  const chatRecommendationRuntime = createChatRecommendationRuntime({
    looksLikeIngredientScienceIntent,
    looksLikeRoutineRequest,
    looksLikeSuitabilityRequest,
    looksLikeRecommendationRequest,
    chatRecoPreludeRuntime,
    chatRecoArtifactRuntime,
    chatRecoResolveRuntime,
  });
  const chatRecommendationFlowRuntime = createChatRecommendationFlowRuntime({
    looksLikeSuitabilityRequest,
    looksLikeCompatibilityOrConflictQuestion,
    looksLikeWeatherOrEnvironmentQuestion,
    looksLikeRecommendationRequest,
    chatRoutineGateRuntime,
    chatRecoEntryRuntime,
    chatRecommendationRuntime,
    chatProfileContinuationRuntime,
  });

  return {
    chatRecoPreludeRuntime,
    chatRecoEntryRuntime,
    chatRecoHandoffRuntime,
    chatRoutineRecoRuntime,
    chatRoutineGateRuntime,
    chatRecoResponseRuntime,
    chatRecoResolveRuntime,
    chatRecoArtifactRuntime,
    chatRecommendationRuntime,
    chatRecommendationFlowRuntime,
  };
}

module.exports = {
  createChatRecommendationRuntimeBundle,
};
