const { createChatFitCheckRuntime } = require('./chatFitCheckRuntime');
const { createChatFollowupRuntime } = require('./chatFollowupRuntime');
const { createChatDerivedCardsRuntime } = require('./chatDerivedCardsRuntime');
const { createChatClarificationRuntime } = require('./chatClarificationRuntime');
const { createChatUpstreamEnvelopeRuntime } = require('./chatUpstreamEnvelopeRuntime');
const { createChatUpstreamResponseRuntime } = require('./chatUpstreamResponseRuntime');
const { createChatUpstreamRequestRuntime } = require('./chatUpstreamRequestRuntime');
const { createChatUpstreamTurnRuntime } = require('./chatUpstreamTurnRuntime');
const { createChatTurnPipelineRuntime } = require('./chatTurnPipelineRuntime');

function createChatTurnPipelineRuntimeBundle(deps = {}) {
  const {
    logger,
    coerceNumber,
    looksLikeSuitabilityRequest,
    normalizeProductAnalysis,
    enrichProductAnalysisPayload,
    finalizeProductAnalysisRecoContract,
    reconcileProductAnalysisConsistency,
    stripInternalRefsDeep,
    extractProductInputFromFitCheckText,
    resolveProductIntelLlmRoute,
    evaluateAnchorTrustForProductIntel,
    AURORA_PRODUCT_STRICT_SKINCARE_FILTER,
    AURORA_RULE_RELAX_AGGRESSIVE,
    extractJsonObjectByKeys,
    mapAuroraProductParse,
    normalizeProductParse,
    canonicalizeIngredientCandidates,
    classifyProductType,
    buildProductDeepScanPrompt,
    auroraChat,
    AURORA_DECISION_BASE_URL,
    AURORA_CHAT_UPSTREAM_TIMEOUT_MS,
    mapAuroraProductAnalysis,
    getProductAnalysisInternalMissingCodes,
    applyProductAnalysisGapContract,
    shouldRetryForNarrativeQuality,
    normalizeProductAnalysisFromUpstream,
    collectNarrativeRetryCodes,
    hasValidNarrativeQuality,
    isProductIntelPayloadCandidateBetter,
    resolveProductIntelEscalationRoute,
    shouldTriggerProductIntelEscalation,
    appendProductIntelSourceChain,
    attachProductIntelLlmRouteProvenance,
    mergeFieldMissing,
    uniqCaseInsensitiveStrings,
    PRODUCT_URL_INGREDIENT_ANALYSIS_ENABLED,
    buildProductAnalysisFromUrlIngredients,
    pickFirstTrimmed,
    buildContextPrefix,
    ANALYSIS_FOLLOWUP_ACTION_IDS,
    buildAnalysisFollowupContent,
    recordAuroraSkinFlowMetric,
    buildConfidenceNoticeCardPayload,
    initCandidateFilterStats,
    buildRealtimeCompetitorCandidates,
    PRODUCT_URL_REALTIME_COMPETITOR_TIMEOUT_MS,
    PRODUCT_URL_REALTIME_COMPETITOR_MAX_QUERIES,
    PRODUCT_URL_REALTIME_COMPETITOR_MAX_CANDIDATES,
    sanitizeCompetitorCandidates,
    routeCompetitorCandidatePools,
    isPlainObject,
    buildEnvStressUiModelFromUpstream,
    buildEnvStressUiModelFromLocal,
    looksLikeWeatherOrEnvironmentQuestion,
    looksLikeCompatibilityOrConflictQuestion,
    extractHeatmapStepsFromConflictDetector,
    buildConflictHeatmapV1,
    CONFLICT_HEATMAP_V1_ENABLED,
    INCLUDE_RAW_AURORA_CONTEXT,
    makeEvent,
    INTENT_ENUM,
    filterClarificationQuestionsForChips,
    normalizeClarificationField,
    hasKnownClarificationFieldValue,
    sanitizePendingClarification,
    buildChipsForQuestion,
    recordClarificationPresent,
    recordRepeatedClarifyField,
    recordClarificationFlowV2Started,
    AURORA_CHAT_CLARIFICATION_FLOW_V2_ENABLED,
    PENDING_CLARIFICATION_SCHEMA_V1,
    makeFlowId,
    getUpstreamStructuredOrJson,
    structuredContainsCommerceLikeFields,
    mergeExternalVerificationIntoStructured,
    isRenderableCardForChatboxUi,
    sanitizeUpstreamAnswer,
    inferRouteFromCards,
    inferRouteFromMessageIntent,
    resolveRouteHint,
    looksLikeGenericStructuredNotice,
    isRouteStructuredAnswer,
    buildRouteAwareAssistantText,
    addEmotionalPreambleToAssistantText,
    stateChangeAllowed,
    recordSessionPatchProfileEmitted,
    emitPendingClarificationPatch,
    isSkincareCatalogCard,
    recordCatalogPoisonBlock,
    looksLikeRoutineRequest,
    hasRoutineSosSignal,
    findRoutineExpertNodeFromEnvelope,
    hasRoutineExpertRequiredModules,
    buildRoutineRulesOnlyFallbackCardsForChat,
    suppressAnalysisCardsForTravelEnvTurn,
    selectTemplate,
    renderAssistantMessage,
    recordTemplateApplied,
    recordTemplateFallback,
    adaptChips,
    looksLikeStallPhrase,
    buildEnvelope,
    stripRecommendationCards,
    enrichRecommendationsWithAlternatives,
    chatPreludeCoordinatorRuntime = null,
    AURORA_CHAT_CLARIFICATION_FILTER_KNOWN_ENABLED,
    ingredientEntityMatchFromText,
    buildIngredientReportPayload,
    buildSkinAnalysisContextForPrefix,
    recordClarificationHistorySent,
    AURORA_CHAT_RESUME_PREFIX_V2_ENABLED,
    AURORA_CHAT_RESUME_PREFIX_V1_ENABLED,
    recordResumePrefixInjected,
    recordResumePrefixHistoryItems,
    recordUpstreamCall,
    observeUpstreamLatency,
    AURORA_CHAT_RESUME_PROBE_METRICS_ENABLED,
    classifyResumeResponseMode,
    recordResumeResponseMode,
    buildResumeKnownProfileFields,
    detectResumePlaintextReaskFields,
    recordResumePlaintextReaskDetected,
  } = deps;

  const chatFitCheckRuntime = createChatFitCheckRuntime({
    logger,
    isPlainObject,
    coerceNumber,
    looksLikeSuitabilityRequest,
    normalizeProductAnalysis,
    enrichProductAnalysisPayload,
    finalizeProductAnalysisRecoContract,
    reconcileProductAnalysisConsistency,
    stripInternalRefsDeep,
    extractProductInputFromFitCheckText,
    resolveProductIntelLlmRoute,
    evaluateAnchorTrustForProductIntel,
    AURORA_PRODUCT_STRICT_SKINCARE_FILTER,
    AURORA_RULE_RELAX_AGGRESSIVE,
    extractJsonObjectByKeys,
    mapAuroraProductParse,
    normalizeProductParse,
    canonicalizeIngredientCandidates,
    classifyProductType,
    buildProductDeepScanPrompt,
    auroraChat,
    AURORA_DECISION_BASE_URL,
    AURORA_CHAT_UPSTREAM_TIMEOUT_MS,
    mapAuroraProductAnalysis,
    getProductAnalysisInternalMissingCodes,
    applyProductAnalysisGapContract,
    shouldRetryForNarrativeQuality,
    normalizeProductAnalysisFromUpstream,
    collectNarrativeRetryCodes,
    hasValidNarrativeQuality,
    isProductIntelPayloadCandidateBetter,
    resolveProductIntelEscalationRoute,
    shouldTriggerProductIntelEscalation,
    appendProductIntelSourceChain,
    attachProductIntelLlmRouteProvenance,
    mergeFieldMissing,
    uniqCaseInsensitiveStrings,
    PRODUCT_URL_INGREDIENT_ANALYSIS_ENABLED,
    buildProductAnalysisFromUrlIngredients,
    pickFirstTrimmed,
    buildContextPrefix,
  });

  const chatFollowupRuntime = createChatFollowupRuntime({
    logger,
    ANALYSIS_FOLLOWUP_ACTION_IDS,
    buildAnalysisFollowupContent,
    recordAuroraSkinFlowMetric,
    pickFirstTrimmed,
    buildConfidenceNoticeCardPayload,
    PRODUCT_URL_INGREDIENT_ANALYSIS_ENABLED,
    buildProductAnalysisFromUrlIngredients,
    applyProductAnalysisGapContract,
    initCandidateFilterStats,
    buildRealtimeCompetitorCandidates,
    PRODUCT_URL_REALTIME_COMPETITOR_TIMEOUT_MS,
    PRODUCT_URL_REALTIME_COMPETITOR_MAX_QUERIES,
    PRODUCT_URL_REALTIME_COMPETITOR_MAX_CANDIDATES,
    sanitizeCompetitorCandidates,
    routeCompetitorCandidatePools,
    uniqCaseInsensitiveStrings,
    asStringArray: deps.asStringArray,
    joinBrandAndName: deps.joinBrandAndName,
    normalizeProductAnalysis,
    reconcileProductAnalysisConsistency,
    finalizeProductAnalysisRecoContract,
    enrichProductAnalysisPayload,
    stripInternalRefsDeep,
    isPlainObject,
  });

  const chatDerivedCardsRuntime = createChatDerivedCardsRuntime({
    isPlainObject,
    chatFitCheckRuntime,
    buildEnvStressUiModelFromUpstream,
    buildEnvStressUiModelFromLocal,
    looksLikeWeatherOrEnvironmentQuestion,
    looksLikeCompatibilityOrConflictQuestion,
    extractHeatmapStepsFromConflictDetector,
    buildConflictHeatmapV1,
    CONFLICT_HEATMAP_V1_ENABLED,
    INCLUDE_RAW_AURORA_CONTEXT,
    makeEvent,
    INTENT_ENUM,
  });

  const chatClarificationRuntime = createChatClarificationRuntime({
    filterClarificationQuestionsForChips,
    normalizeClarificationField,
    hasKnownClarificationFieldValue,
    sanitizePendingClarification,
    buildChipsForQuestion,
    recordClarificationPresent,
    recordRepeatedClarifyField,
    recordClarificationFlowV2Started,
    AURORA_CHAT_CLARIFICATION_FLOW_V2_ENABLED,
    PENDING_CLARIFICATION_SCHEMA_V1,
    makeFlowId,
  });

  const chatUpstreamEnvelopeRuntime = createChatUpstreamEnvelopeRuntime({
    logger,
    getUpstreamStructuredOrJson,
    structuredContainsCommerceLikeFields,
    mergeExternalVerificationIntoStructured,
    isRenderableCardForChatboxUi,
    sanitizeUpstreamAnswer,
    inferRouteFromCards,
    inferRouteFromMessageIntent,
    resolveRouteHint,
    looksLikeGenericStructuredNotice,
    isRouteStructuredAnswer,
    buildRouteAwareAssistantText,
    addEmotionalPreambleToAssistantText,
    stripInternalRefsDeep,
    finalizeProductAnalysisRecoContract,
    stateChangeAllowed,
    recordSessionPatchProfileEmitted,
    emitPendingClarificationPatch,
    isSkincareCatalogCard,
    recordCatalogPoisonBlock,
    looksLikeRoutineRequest,
    hasRoutineSosSignal,
    findRoutineExpertNodeFromEnvelope,
    hasRoutineExpertRequiredModules,
    buildRoutineRulesOnlyFallbackCardsForChat,
    suppressAnalysisCardsForTravelEnvTurn,
    selectTemplate,
    renderAssistantMessage,
    recordTemplateApplied,
    recordTemplateFallback,
    adaptChips,
    looksLikeStallPhrase,
    buildEnvelope,
    makeEvent,
    AURORA_CATALOG_DOMAIN_GUARD_V1_ENABLED: deps.AURORA_CATALOG_DOMAIN_GUARD_V1_ENABLED,
  });

  const chatUpstreamResponseRuntime = createChatUpstreamResponseRuntime({
    logger,
    stripRecommendationCards,
    enrichRecommendationsWithAlternatives,
    mergeFieldMissing,
    chatClarificationRuntime,
    chatDerivedCardsRuntime,
    chatUpstreamEnvelopeRuntime,
    AURORA_CHAT_CLARIFICATION_FILTER_KNOWN_ENABLED,
  });

  const chatUpstreamRequestRuntime = createChatUpstreamRequestRuntime({
    logger,
    ingredientEntityMatchFromText,
    buildIngredientReportPayload,
    buildSkinAnalysisContextForPrefix,
    buildContextPrefix,
    recordClarificationHistorySent,
    AURORA_CHAT_RESUME_PREFIX_V2_ENABLED,
    AURORA_CHAT_RESUME_PREFIX_V1_ENABLED,
    recordResumePrefixInjected,
    recordResumePrefixHistoryItems,
    auroraChat,
    AURORA_DECISION_BASE_URL,
    AURORA_CHAT_UPSTREAM_TIMEOUT_MS,
    recordUpstreamCall,
    observeUpstreamLatency,
    AURORA_CHAT_RESUME_PROBE_METRICS_ENABLED,
    classifyResumeResponseMode,
    recordResumeResponseMode,
    buildResumeKnownProfileFields,
    detectResumePlaintextReaskFields,
    recordResumePlaintextReaskDetected,
  });

  const chatUpstreamTurnRuntime = createChatUpstreamTurnRuntime({
    chatUpstreamRequestRuntime,
    chatUpstreamResponseRuntime,
  });

  const chatTurnPipelineRuntime = createChatTurnPipelineRuntime({
    chatFollowupRuntime,
    chatPreludeCoordinatorRuntime,
    chatUpstreamTurnRuntime,
  });

  return {
    chatClarificationRuntime,
    chatDerivedCardsRuntime,
    chatFitCheckRuntime,
    chatFollowupRuntime,
    chatTurnPipelineRuntime,
    chatUpstreamEnvelopeRuntime,
    chatUpstreamRequestRuntime,
    chatUpstreamResponseRuntime,
    chatUpstreamTurnRuntime,
  };
}

module.exports = {
  createChatTurnPipelineRuntimeBundle,
};
