const { createChatAdvisoryRuntime } = require('./chatAdvisoryRuntime');
const { createChatSafetyRuntime } = require('./chatSafetyRuntime');
const { createChatBoundaryRuntime } = require('./chatBoundaryRuntime');
const { createChatBoundaryPreludeRuntime } = require('./chatBoundaryPreludeRuntime');
const { createChatLoopBreakerRuntime } = require('./chatLoopBreakerRuntime');
const { createChatTravelEnvRuntime } = require('./chatTravelEnvRuntime');
const { createChatDiagnosisGateRuntime } = require('./chatDiagnosisGateRuntime');
const { createChatProfileContinuationRuntime } = require('./chatProfileContinuationRuntime');
const { createChatIngredientLookupRuntime } = require('./chatIngredientLookupRuntime');
const { createChatIngredientEntryRuntime } = require('./chatIngredientEntryRuntime');
const { createChatIngredientPreludeRuntime } = require('./chatIngredientPreludeRuntime');
const { createChatConflictRuntime } = require('./chatConflictRuntime');
const { createChatCatalogAvailabilityRuntime } = require('./chatCatalogAvailabilityRuntime');
const { createChatTurnStateRuntime } = require('./chatTurnStateRuntime');

function createChatPreludeRuntimeBundle(options = {}) {
  const {
    logger,
    isPlainObject,
    makeEvent,
    DEFAULT_AGENT_STATE,
    INTENT_ENUM,
    BLOCK_LEVEL,
    GATE_MODE,
    OPTIONAL_SAFETY_PROFILE_FIELDS,
    profileHasOptionalSafetyFieldValue,
    normalizeSafetyPromptStateForChat,
    buildSafetyAdvisoryChipsByField,
    upsertProfileForIdentity,
    collectConceptMatchesFromText,
    matchIngredientOntology,
    evaluateSafety,
    buildFitCheckAnchorPrompt,
    buildConfidenceNoticeCardPayload,
    resolveQaPlan,
    stateChangeAllowed,
    looksLikeSuitabilityRequest,
    looksLikeCompatibilityOrConflictQuestion,
    looksLikeRoutineRequest,
    looksLikeRecommendationRequest,
    looksLikeWeatherOrEnvironmentQuestion,
    AURORA_CHAT_NONBLOCKING_GATE_V1_ENABLED,
    extractWeatherScenario,
    buildEnvStressUiModelFromLocal,
    buildWeatherAdviceMessage,
    resolvePreferredLegacyTravelPlan,
    runTravelPipeline,
    getOpenAIClient,
    recordAuroraTravelEnvCardEmitted,
    getTravelWeather,
    buildEpiPayload,
    normalizeEnvStressTier,
    buildEpiRadarRows,
    buildTravelReadinessFromEpi,
    buildEnvStressTierDescription,
    AURORA_CHAT_CLARIFICATION_FLOW_V2_ENABLED,
    buildPendingClarificationForGate,
    emitPendingClarificationPatch,
    profileCompleteness,
    recordSessionPatchProfileEmitted,
    pickFirstTrimmed,
    normalizeIngredientRecoContextValue,
    mergeIngredientRecoContextValue,
    ingredientEntityMatchFromText,
    resolveIngredientReferenceRuntimeMatch,
    resolveIngredientSignalRuntimeMatch,
    shouldPreferSignalRuntimeMatch,
    normalizeIngredientResearchKey,
    checkIngredientLookupRateLimit,
    getIngredientResearchCache,
    getIngredientResearchKbEntry,
    touchIngredientResearchCache,
    INGREDIENT_ROUTE_V2_ENABLED,
    INGREDIENT_LEGACY_PATH_ENABLED,
    AURORA_INGREDIENT_LLM_REPORT_ENABLED,
    runIngredientResearchSync,
    asResearchObject,
    getIngredientProviderCircuitState,
    INGREDIENT_KB_ONLY_MODE,
    enqueueIngredientResearchJob,
    buildIngredientReportPayload,
    buildIngredientReportQuickReplyChips,
    recordAuroraIngredientsFlowMetric,
    INGREDIENT_ROUTE_RULE_VERSION,
    buildIngredientHubCardPayload,
    buildIngredientHubQuickReplyChips,
    buildIngredientGoalMatchPayload,
    enrichIngredientGoalMatchPayload,
    buildIngredientScienceKickoff,
    isIngredientEntryAction,
    isIngredientLookupAction,
    isIngredientByGoalAction,
    isIngredientDiagnosisOptInAction,
    isIngredientResearchPollAction,
    isIngredientRecoOptInAction,
    extractIngredientLookupQuery,
    extractIngredientLookupTargetFromText,
    looksLikeProductEvaluationIntentV2,
    extractIngredientGoalRequest,
    extractActionDataObject,
    extractIngredientRecoContext,
    normalizeIngredientCandidateList,
    normalizeIngredientActionId,
    buildIngredientLookupUpstreamPrompt,
    buildIngredientRecoUpstreamPrompt,
    normalizeAgentState,
    deriveRequestedTransitionFromAction,
    inferTextExplicitTransition,
    validateRequestedTransition,
    recommendationsAllowed,
    isClarifyChipAction,
    hasPendingClarificationStateHint,
    parseClarificationReplyFromActionId,
    extractClarificationQuestionIdFromAction,
    parseClarificationIdFromActionId,
    advancePendingClarification,
    compactClarificationHistory,
    looksLikeDiagnosisStart,
    buildLocalCompatibilitySimulationInput,
    simulateConflicts,
    buildHeatmapStepsFromRoutine,
    buildConflictHeatmapV1,
    CONFLICT_HEATMAP_V1_ENABLED,
    detectCatalogAvailabilityIntent,
    AURORA_CATALOG_DOMAIN_GUARD_V1_ENABLED,
    shouldAllowCatalogAvailabilityShortCircuit,
    detectCatalogAvailabilityShortCircuitBlockReason,
    recordCatalogAvailabilityShortCircuit,
    buildAvailabilityCatalogQuery,
    isSpecificAvailabilityQuery,
    buildBrandPlaceholderProduct,
    PIVOTA_BACKEND_BASE_URL,
    searchPivotaBackendProducts,
    CATALOG_AVAIL_SEARCH_TIMEOUT_MS,
    CATALOG_AVAIL_RESOLVE_FALLBACK_ENABLED,
    CATALOG_AVAIL_RESOLVE_FALLBACK_ON_TRANSIENT,
    resolveAvailabilityProductByQuery,
    RECO_PDP_STRICT_INTERNAL_FIRST,
    resolveAvailabilityProductByLocalResolver,
    isSkincareCatalogProduct,
    recordCatalogPoisonBlock,
    applyOfferItemPdpOpenContract,
    summarizeOfferPdpOpen,
    applyCommerceMedicalClaimGuard,
    buildResumeKnownProfileFields,
    PENDING_CLARIFICATION_TTL_MS,
  } = options;

  const chatTurnStateRuntime = createChatTurnStateRuntime({
    DEFAULT_AGENT_STATE,
    AURORA_CHAT_CLARIFICATION_FLOW_V2_ENABLED,
    PENDING_CLARIFICATION_TTL_MS,
    normalizeAgentState,
    deriveRequestedTransitionFromAction,
    inferTextExplicitTransition,
    validateRequestedTransition,
    recommendationsAllowed,
    isClarifyChipAction,
    hasPendingClarificationStateHint,
    parseClarificationReplyFromActionId,
    extractClarificationQuestionIdFromAction,
    parseClarificationIdFromActionId,
    advancePendingClarification,
    emitPendingClarificationPatch,
    compactClarificationHistory,
    buildResumeKnownProfileFields,
  });
  const chatAdvisoryRuntime = createChatAdvisoryRuntime({
    logger,
    isPlainObject,
    makeEvent,
    BLOCK_LEVEL,
    GATE_MODE,
    OPTIONAL_SAFETY_PROFILE_FIELDS,
    profileHasOptionalSafetyFieldValue,
    normalizeSafetyPromptStateForChat,
    buildSafetyAdvisoryChipsByField,
    upsertProfileForIdentity,
  });
  const chatSafetyRuntime = createChatSafetyRuntime({
    chatAdvisoryRuntime,
    INTENT_ENUM,
  });
  const chatBoundaryRuntime = createChatBoundaryRuntime({
    logger,
    collectConceptMatchesFromText,
    matchIngredientOntology,
    evaluateSafety,
    buildFitCheckAnchorPrompt,
    buildConfidenceNoticeCardPayload,
    chatSafetyRuntime,
    INTENT_ENUM,
    BLOCK_LEVEL,
    GATE_MODE,
  });
  const chatBoundaryPreludeRuntime = createChatBoundaryPreludeRuntime({
    resolveQaPlan,
    stateChangeAllowed,
    looksLikeSuitabilityRequest,
    looksLikeCompatibilityOrConflictQuestion,
    looksLikeRoutineRequest,
    looksLikeRecommendationRequest,
    looksLikeWeatherOrEnvironmentQuestion,
    chatBoundaryRuntime,
  });
  const chatLoopBreakerRuntime = createChatLoopBreakerRuntime({
    INTENT_ENUM,
  });
  const chatTravelEnvRuntime = createChatTravelEnvRuntime({
    logger,
    INTENT_ENUM,
    GATE_MODE,
    BLOCK_LEVEL,
    AURORA_CHAT_NONBLOCKING_GATE_V1_ENABLED,
    looksLikeWeatherOrEnvironmentQuestion,
    extractWeatherScenario,
    buildEnvStressUiModelFromLocal,
    buildWeatherAdviceMessage,
    resolvePreferredLegacyTravelPlan,
    runTravelPipeline,
    getOpenAIClient,
    recordAuroraTravelEnvCardEmitted,
    getTravelWeather,
    buildEpiPayload,
    normalizeEnvStressTier,
    buildEpiRadarRows,
    buildTravelReadinessFromEpi,
    buildEnvStressTierDescription,
    stateChangeAllowed,
  });
  const chatDiagnosisGateRuntime = createChatDiagnosisGateRuntime({
    logger,
    GATE_MODE,
    AURORA_CHAT_CLARIFICATION_FLOW_V2_ENABLED,
    buildPendingClarificationForGate,
    emitPendingClarificationPatch,
  });
  const chatProfileContinuationRuntime = createChatProfileContinuationRuntime({
    profileCompleteness,
    stateChangeAllowed,
    recordSessionPatchProfileEmitted,
    chatDiagnosisGateRuntime,
  });
  const chatIngredientLookupRuntime = createChatIngredientLookupRuntime({
    logger,
    isPlainObject,
    pickFirstTrimmed,
    normalizeIngredientRecoContextValue,
    mergeIngredientRecoContextValue,
    ingredientEntityMatchFromText,
    resolveIngredientReferenceRuntimeMatch,
    resolveIngredientSignalRuntimeMatch,
    shouldPreferSignalRuntimeMatch,
    normalizeIngredientResearchKey,
    checkIngredientLookupRateLimit,
    getIngredientResearchCache,
    getIngredientResearchKbEntry,
    touchIngredientResearchCache,
    INGREDIENT_ROUTE_V2_ENABLED,
    INGREDIENT_LEGACY_PATH_ENABLED,
    AURORA_INGREDIENT_LLM_REPORT_ENABLED,
    runIngredientResearchSync,
    asResearchObject,
    getIngredientProviderCircuitState,
    INGREDIENT_KB_ONLY_MODE,
    enqueueIngredientResearchJob,
    buildIngredientReportPayload,
    buildIngredientReportQuickReplyChips,
    stateChangeAllowed,
    recordAuroraIngredientsFlowMetric,
    INGREDIENT_ROUTE_RULE_VERSION,
  });
  const chatIngredientEntryRuntime = createChatIngredientEntryRuntime({
    logger,
    pickFirstTrimmed,
    mergeIngredientRecoContextValue,
    buildIngredientHubCardPayload,
    buildIngredientHubQuickReplyChips,
    buildIngredientGoalMatchPayload,
    enrichIngredientGoalMatchPayload,
    buildIngredientScienceKickoff,
    stateChangeAllowed,
    recordAuroraIngredientsFlowMetric,
    chatIngredientLookupRuntime,
  });
  const chatIngredientPreludeRuntime = createChatIngredientPreludeRuntime({
    isIngredientEntryAction,
    isIngredientLookupAction,
    isIngredientByGoalAction,
    isIngredientDiagnosisOptInAction,
    isIngredientResearchPollAction,
    isIngredientRecoOptInAction,
    extractIngredientLookupQuery,
    extractIngredientLookupTargetFromText,
    ingredientEntityMatchFromText,
    looksLikeProductEvaluationIntentV2,
    looksLikeRecommendationRequest,
    looksLikeSuitabilityRequest,
    extractIngredientGoalRequest,
    extractActionDataObject,
    normalizeIngredientRecoContextValue,
    mergeIngredientRecoContextValue,
    extractIngredientRecoContext,
    normalizeIngredientCandidateList,
    pickFirstTrimmed,
    normalizeIngredientActionId,
    recordAuroraIngredientsFlowMetric,
    buildIngredientLookupUpstreamPrompt,
    buildIngredientRecoUpstreamPrompt,
    looksLikeCompatibilityOrConflictQuestion,
    looksLikeRoutineRequest,
    normalizeAgentState,
    looksLikeDiagnosisStart,
  });
  const chatConflictRuntime = createChatConflictRuntime({
    looksLikeCompatibilityOrConflictQuestion,
    buildLocalCompatibilitySimulationInput,
    simulateConflicts,
    buildHeatmapStepsFromRoutine,
    buildConflictHeatmapV1,
    buildRouteAwareAssistantText: options.buildRouteAwareAssistantText,
    addEmotionalPreambleToAssistantText: options.addEmotionalPreambleToAssistantText,
    stateChangeAllowed,
    CONFLICT_HEATMAP_V1_ENABLED,
  });
  const chatCatalogAvailabilityRuntime = createChatCatalogAvailabilityRuntime({
    logger,
    AURORA_CATALOG_DOMAIN_GUARD_V1_ENABLED,
    detectCatalogAvailabilityIntent,
    shouldAllowCatalogAvailabilityShortCircuit,
    detectCatalogAvailabilityShortCircuitBlockReason,
    recordCatalogAvailabilityShortCircuit,
    buildAvailabilityCatalogQuery,
    isSpecificAvailabilityQuery,
    buildBrandPlaceholderProduct,
    PIVOTA_BACKEND_BASE_URL,
    searchPivotaBackendProducts,
    CATALOG_AVAIL_SEARCH_TIMEOUT_MS,
    CATALOG_AVAIL_RESOLVE_FALLBACK_ENABLED,
    CATALOG_AVAIL_RESOLVE_FALLBACK_ON_TRANSIENT,
    resolveAvailabilityProductByQuery,
    RECO_PDP_STRICT_INTERNAL_FIRST,
    resolveAvailabilityProductByLocalResolver,
    isSkincareCatalogProduct,
    recordCatalogPoisonBlock,
    applyOfferItemPdpOpenContract,
    summarizeOfferPdpOpen,
    applyCommerceMedicalClaimGuard,
    stateChangeAllowed,
    recordSessionPatchProfileEmitted,
  });

  return {
    chatTurnStateRuntime,
    chatAdvisoryRuntime,
    chatSafetyRuntime,
    chatBoundaryRuntime,
    chatBoundaryPreludeRuntime,
    chatLoopBreakerRuntime,
    chatTravelEnvRuntime,
    chatDiagnosisGateRuntime,
    chatProfileContinuationRuntime,
    chatIngredientLookupRuntime,
    chatIngredientEntryRuntime,
    chatIngredientPreludeRuntime,
    chatConflictRuntime,
    chatCatalogAvailabilityRuntime,
  };
}

module.exports = {
  createChatPreludeRuntimeBundle,
};
