const {
  createLegacyChatRecoResultPipelineRuntime,
} = require('./legacyChatRecoResultPipeline');
const {
  createLegacyChatRecoContextPipelineRuntime,
} = require('./legacyChatRecoContextPipeline');

async function handleLegacyChatRecoRequest({
  ctx,
  message,
  profile,
  session,
  recentLogs,
  logger,
  identity,
  attachAnalysisContextUsageToSessionPatch,
  canonicalIntent,
  safetyDecision,
  buildSafetyNoticeText,
  includeAlternatives,
  actionId,
  debugUpstream,
  requestScopedProfileOverride,
  ingredientRecoContext,
  ingredientRecoOptInRequested,
  ingredientActionData,
  ingredientDrivenRecommendationRequested,
  latestRecoContextFromSession,
  recoEntrySourceDetail,
  recoRequestMessage,
  shouldAutoRerunRecommendationsFromProfilePatch,
  travelSkillsContracts,
  looksLikeLowRiskSkincareTask,
  runAuroraTimedOperation,
  ensureLatestArtifactForConversation,
  ensureAnalysisContextSnapshotForConversation,
  ensureTaskAnalysisContextForConversation,
  getIngredientPlanByArtifactIdForRoute,
  getAuroraStorageReadTimeoutMs,
  saveIngredientPlanForRoute,
  getAuroraStorageWriteTimeoutMs,
  prepareLegacyChatRecoContext,
  buildLegacyRecoSafetyGateEnvelope,
  maybeBuildLegacyTravelRecoEnvelope,
  prepareLegacyChatRecoAnalysisContext,
  prepareLegacyChatRecoTargeting,
  postProcessLegacyChatRecoResult,
  normalizeLegacyChatRecoPayload,
  finalizeLegacyChatRecoEnvelope,
  resolveSafetyGateActionV2,
  mergePendingSafetyAdvisory,
  persistSafetyPromptAskedOnce,
  profileCompleteness,
  buildPendingClarificationForGate,
  emitPendingClarificationPatch,
  buildDiagnosisChips,
  evaluateSafetyBoundary,
  buildConfidenceNoticeCardPayload,
  buildIngredientPlan,
  buildProductRecommendationsBundle,
  toLegacyRecommendationsPayload,
  shouldUseLegacyVerifiedContextRestore,
  restoreRecoRecommendationsFromVerifiedContextCandidates,
  applyVerifiedCandidateRestoreToRecoPayload,
  summarizeProfileForContext,
  normalizeRecoSourceDetail,
  generateProductRecommendations,
  extractRecoContextProductCandidatesFromCandidatePoolState,
  buildIngredientRecoContextTargetBundle,
  normalizeRecoTargetStep,
  mergeIngredientRecoContextValue,
  classifyRecoUpstreamFailureCode,
  isTransientRecoUpstreamFailureCode,
  recordAuroraRecoLlmCall,
  normalizeRecoFailureClass,
  recordAuroraSkinFlowMetric,
  recordAuroraRecoEntrySource,
  AURORA_CHAT_CLARIFICATION_FLOW_V2_ENABLED,
  AURORA_INGREDIENT_PLAN_ENABLED,
  AURORA_PRODUCT_MATCHER_ENABLED,
  AURORA_CHAT_NONBLOCKING_GATE_V1_ENABLED,
  MINIMUM_RECOMMENDATION_CONTEXT_RULE_VERSION,
  AURORA_PRODUCT_MATCHER_BUNDLED_SEED_FALLBACK_ENABLED,
  DIAG_PRODUCT_CATALOG_PATH,
  AURORA_BFF_CHAT_RECO_BUDGET_MS,
} = {}) {
  const {
    prepareLegacyChatRecoRequestContext,
  } = createLegacyChatRecoContextPipelineRuntime({
    prepareLegacyChatRecoContext,
    prepareLegacyChatRecoAnalysisContext,
    prepareLegacyChatRecoTargeting,
    resolveSafetyGateActionV2,
    mergePendingSafetyAdvisory,
    persistSafetyPromptAskedOnce,
    buildLegacyRecoSafetyGateEnvelope,
    buildSafetyNoticeText,
    profileCompleteness,
    buildPendingClarificationForGate,
    emitPendingClarificationPatch,
    buildDiagnosisChips,
    evaluateSafetyBoundary,
    buildConfidenceNoticeCardPayload,
    maybeBuildLegacyTravelRecoEnvelope,
    recordAuroraSkinFlowMetric,
    recordAuroraRecoEntrySource,
    AURORA_CHAT_CLARIFICATION_FLOW_V2_ENABLED,
    AURORA_INGREDIENT_PLAN_ENABLED,
    AURORA_PRODUCT_MATCHER_ENABLED,
    AURORA_CHAT_NONBLOCKING_GATE_V1_ENABLED,
    MINIMUM_RECOMMENDATION_CONTEXT_RULE_VERSION,
  });
  const preparedRequestContext = await prepareLegacyChatRecoRequestContext({
    ctx,
    message,
    profile,
    session,
    recentLogs,
    logger,
    identity,
    canonicalIntent,
    safetyDecision,
    includeAlternatives,
    actionId,
    ingredientRecoContext,
    ingredientRecoOptInRequested,
    ingredientActionData,
    ingredientDrivenRecommendationRequested,
    latestRecoContextFromSession,
    recoEntrySourceDetail,
    recoRequestMessage,
    travelSkillsContracts,
    looksLikeLowRiskSkincareTask,
    runAuroraTimedOperation,
    ensureLatestArtifactForConversation,
    ensureAnalysisContextSnapshotForConversation,
    ensureTaskAnalysisContextForConversation,
    getIngredientPlanByArtifactIdForRoute,
    getAuroraStorageReadTimeoutMs,
    saveIngredientPlanForRoute,
    getAuroraStorageWriteTimeoutMs,
  });
  if (preparedRequestContext.envelope) return preparedRequestContext.envelope;

  const {
    profileScore,
    refinementChips,
    pendingClarificationPatchOverride,
    analysisContextSnapshotForConversation,
    chatAnalysisTaskContext,
    latestArtifact,
    artifactGate,
    mappedIngredientPlan,
    recoIngredientContext,
    recoContextIngredientQuery,
    recoContextGoal,
    recoIngredientCandidates,
    recoProductCandidates,
    travelRecoHandoff,
    shouldApplySessionRecoContext,
    effectiveRecoEntrySourceDetail,
    recoTaskMode,
    recoAutoAnchoredByAnalysis,
    recoIngredientContextForMainline,
    catalogExternalSeedStrategyForMainline,
    recoRequestMessageForMainline,
    recoFocusForMainline,
    chatRecoTargetContext,
    latestRecoContextPatch,
    hasDeterministicRecoTarget,
    hasStableRecoTarget,
    genericConcernRecoMainline,
  } = preparedRequestContext;

  const hasRecoArtifact = Boolean(latestArtifact && typeof latestArtifact === 'object' && !Array.isArray(latestArtifact));
  const artifactConfidenceLevel =
    hasRecoArtifact && artifactGate && artifactGate.confidence_level
      ? artifactGate.confidence_level
      : 'unknown';
  const lowConfidenceArtifact = hasRecoArtifact && artifactConfidenceLevel === 'low';
  const artifactConfidenceScoreRaw = Number(
    latestArtifact &&
    latestArtifact.overall_confidence &&
    latestArtifact.overall_confidence.score,
  );
  const artifactConfidenceScore = Number.isFinite(artifactConfidenceScoreRaw) ? artifactConfidenceScoreRaw : null;
  const {
    runLegacyChatRecoResultPipeline,
  } = createLegacyChatRecoResultPipelineRuntime({
    buildIngredientPlan,
    buildProductRecommendationsBundle,
    toLegacyRecommendationsPayload,
    summarizeProfileForContext,
    normalizeRecoSourceDetail,
    shouldUseLegacyVerifiedContextRestore,
    restoreRecoRecommendationsFromVerifiedContextCandidates,
    applyVerifiedCandidateRestoreToRecoPayload,
    generateProductRecommendations,
    extractRecoContextProductCandidatesFromCandidatePoolState,
    buildIngredientRecoContextTargetBundle,
    normalizeRecoTargetStep,
    mergeIngredientRecoContextValue,
    classifyRecoUpstreamFailureCode,
    isTransientRecoUpstreamFailureCode,
    recordAuroraRecoLlmCall,
    normalizeRecoFailureClass,
    postProcessLegacyChatRecoResult,
    normalizeLegacyChatRecoPayload,
    finalizeLegacyChatRecoEnvelope,
  });
  return runLegacyChatRecoResultPipeline({
    ctx,
    profile,
    recentLogs,
    message,
    includeAlternatives,
    logger,
    ingredientRecoOptInRequested,
    travelRecoHandoff,
    shouldApplySessionRecoContext,
    recoAutoAnchoredByAnalysis,
    effectiveRecoEntrySourceDetail,
    hasStableRecoTarget,
    recoIngredientContext,
    latestRecoContextPatch,
    chatRecoTargetContext,
    recoTaskMode,
    artifactConfidenceScore,
    artifactConfidenceLevel,
    lowConfidenceArtifact,
    recoContextIngredientQuery,
    recoContextGoal,
    recoIngredientCandidates,
    latestArtifact,
    mappedIngredientPlan,
    analysisContextSnapshotForConversation,
    requestScopedProfileOverride,
    debugUpstream,
    recoRequestMessageForMainline,
    recoFocusForMainline,
    recoIngredientContextForMainline,
    catalogExternalSeedStrategyForMainline,
    recoProductCandidates,
    genericConcernRecoMainline,
    hasDeterministicRecoTarget,
    buildSafetyNoticeText,
    shouldAutoRerunRecommendationsFromProfilePatch,
    recoRequestMessage,
    safetyDecision,
    chatAnalysisTaskContext,
    attachAnalysisContextUsageToSessionPatch,
    identity,
    refinementChips,
    pendingClarificationPatchOverride,
    profileScore,
    productMatcherEnabled: AURORA_PRODUCT_MATCHER_ENABLED,
    productMatcherBundledSeedFallbackEnabled:
      AURORA_PRODUCT_MATCHER_BUNDLED_SEED_FALLBACK_ENABLED,
    diagProductCatalogPath: DIAG_PRODUCT_CATALOG_PATH,
    recoBudgetMs: AURORA_BFF_CHAT_RECO_BUDGET_MS,
    AURORA_PRODUCT_MATCHER_ENABLED,
  });
}

module.exports = {
  handleLegacyChatRecoRequest,
};
