'use strict';

// Lever-2 review-priority model for the SKU relation graph.
//
// Purpose: the generator's score_total is a retrieval-similarity score that
// saturates near 1.0 and does NOT predict reviewer approval (validated
// 2026-05-31: score_total AUC=0.55 against human labels). This module scores a
// review-pending candidate by its *probability of human approval* so the
// review queue can be ranked highest-yield-first.
//
// Scope: a RANKING aid only. Validated ceiling on the labeled set is CV AUC
// 0.738 with precision@top-5%=0.75 — useful for ordering review but NOT
// sufficient for auto-promotion (which needs ~0.9+). Edges still require human
// approval to become served.
//
// Model: standardized logistic regression. Coefficients live in the committed
// artifact relationshipReviewPriorityModel.json, regenerated by
// scripts/train-review-priority-model.js. extractFeatures is shared by the
// trainer and inference to guarantee train/serve parity.

const path = require('node:path');

// Feature order is the contract between the trainer and the artifact. Do not
// reorder without retraining.
const FEATURE_NAMES = [
  'targetAreaMatch',     // 1 same, 0 differ, 0.5 unknown
  'categoryTokenOverlap',// 1 share a canonical category token, 0 none, 0.5 unknown
  'productFormMatch',    // tri-state
  'scentMatch',          // tri-state
  'skinConcernJaccard',  // 0..1, 0.5 when unknown
  'sameBrand',           // 1 same brand, 0 cross/unknown
  'claimRiskMatch',      // tri-state
  'scoreTotal',          // raw generator similarity (0..1)
  'isRelatedProduct',    // 1 for related_product relation
  'multiArea',           // 1 if either side targets multi_area
];

function tri(a, b) {
  if (a == null || b == null) return 0.5;
  return a === b ? 1 : 0;
}

function jaccard(a, b) {
  const A = Array.isArray(a) ? a : [];
  const B = Array.isArray(b) ? b : [];
  if (!A.length && !B.length) return null;
  const setB = new Set(B);
  let inter = 0;
  for (const x of new Set(A)) if (setB.has(x)) inter += 1;
  const union = new Set([...A, ...B]).size;
  return union ? inter / union : null;
}

// Shared with productRelationshipGraphPreflight; kept local to avoid a cycle.
const STOP = require('./productRelationshipGraphPreflight').CATEGORY_LEAF_STOP_TOKENS;
const ALIASES = require('./productRelationshipGraphPreflight').CATEGORY_LEAF_ALIASES;
function leafTokens(leaf) {
  if (!leaf || typeof leaf !== 'string') return new Set();
  const out = new Set();
  for (const t of leaf.split('_')) {
    if (!t || STOP.has(t)) continue;
    out.add(ALIASES[t] || t);
  }
  return out;
}
function shareToken(a, b) {
  const ta = leafTokens(a); const tb = leafTokens(b);
  if (!ta.size || !tb.size) return null;
  for (const t of ta) if (tb.has(t)) return true;
  return false;
}

// Returns the RAW (pre-standardization) feature vector in FEATURE_NAMES order.
// Always fully defined (neutral 0.5 / 0 fallbacks) so there is no imputation
// skew between train and serve.
function extractFeatures({ anchorAttrs, candidateAttrs, relationType, scoreTotal, anchorBrand, candidateBrand } = {}) {
  const a = anchorAttrs || {};
  const c = candidateAttrs || {};
  const overlap = shareToken(a.category_leaf, c.category_leaf);
  const jac = jaccard(a.skin_concern, c.skin_concern);
  return [
    tri(a.target_area, c.target_area),
    overlap == null ? 0.5 : (overlap ? 1 : 0),
    tri(a.product_form, c.product_form),
    tri(a.scent_family, c.scent_family),
    jac == null ? 0.5 : jac,
    (anchorBrand && candidateBrand && anchorBrand === candidateBrand) ? 1 : 0,
    tri(a.claim_risk_level, c.claim_risk_level),
    Number.isFinite(Number(scoreTotal)) ? Number(scoreTotal) : 0,
    relationType === 'related_product' ? 1 : 0,
    (a.target_area === 'multi_area' || c.target_area === 'multi_area') ? 1 : 0,
  ];
}

function loadModel() {
  // Lazy require so the module loads even before the artifact is generated.
  // eslint-disable-next-line global-require, import/no-unresolved
  try {
    return require(path.join(__dirname, 'relationshipReviewPriorityModel.json'));
  } catch {
    return null;
  }
}

const MODEL = loadModel();

function sigmoid(z) { return 1 / (1 + Math.exp(-z)); }

// Predicted P(human approves) in [0,1]. Returns null if no model artifact is
// present (callers should treat null as "unscored", not low priority).
function computeReviewPriority(input, model = MODEL) {
  if (!model || !Array.isArray(model.weights)) return null;
  const x = extractFeatures(input);
  let z = model.intercept || 0;
  for (let j = 0; j < x.length; j += 1) {
    const sd = model.sd[j] || 1;
    z += model.weights[j] * ((x[j] - (model.mean[j] || 0)) / sd);
  }
  return Number(sigmoid(z).toFixed(4));
}

module.exports = {
  FEATURE_NAMES,
  extractFeatures,
  computeReviewPriority,
  loadModel,
  MODEL,
};
