const jpLookSpecLexicon = {
  market: 'JP',
  base: {
    finish: ['matte', 'natural', 'satin', 'dewy', 'unknown'],
    coverage: ['sheer', 'light', 'medium', 'full', 'unknown'],
  },
  eye: {
    shadowShape: ['washed', 'defined_crease', 'smoky', 'winged', 'halo', 'gradient', 'unknown'],
    linerDirection: { direction: ['down', 'straight', 'up', 'unknown'], degreeMin: -20, degreeMax: 20 },
    lashIntensity: ['none', 'light', 'medium', 'bold', 'unknown'],
  },
  lip: {
    finish: ['matte', 'satin', 'gloss', 'tint', 'hydrated', 'unknown'],
  },
  vibeTags: {
    ids: [
      'jp_clear_soft',
      'jp_clean_minimal',
      'jp_translucent_glow',
      'jp_soft_matte',
      'jp_natural_daily',
      'jp_cute_sweet',
      'jp_cool_mode',
      'jp_warm_gentle',
      'jp_elegant',
      'jp_romantic',
      'jp_fresh_young',
      'jp_office',
      'jp_party',
      'jp_y2k',
      'jp_retro',
      'jp_doll_like',
      'jp_airy',
      'jp_glossy_lip',
      'jp_smoky_eye',
      'jp_bold_liner',
    ],
    display: {
      jp_clear_soft: { ja: '透明感', en: 'clear/soft' },
      jp_clean_minimal: { ja: 'クリーン', en: 'clean/minimal' },
      jp_translucent_glow: { ja: 'ツヤ', en: 'translucent glow' },
      jp_soft_matte: { ja: 'ソフトマット', en: 'soft matte' },
      jp_natural_daily: { ja: 'ナチュラル', en: 'natural daily' },
      jp_cute_sweet: { ja: '可愛い', en: 'cute/sweet' },
      jp_cool_mode: { ja: 'クール', en: 'cool' },
      jp_warm_gentle: { ja: '温かい', en: 'warm/gentle' },
      jp_elegant: { ja: '上品', en: 'elegant' },
      jp_romantic: { ja: 'ロマンティック', en: 'romantic' },
      jp_fresh_young: { ja: 'フレッシュ', en: 'fresh' },
      jp_office: { ja: 'オフィス', en: 'office' },
      jp_party: { ja: 'パーティー', en: 'party' },
      jp_y2k: { ja: 'Y2K', en: 'y2k' },
      jp_retro: { ja: 'レトロ', en: 'retro' },
      jp_doll_like: { ja: 'ドール', en: 'doll-like' },
      jp_airy: { ja: 'ふんわり', en: 'airy' },
      jp_glossy_lip: { ja: 'うるツヤリップ', en: 'glossy lip' },
      jp_smoky_eye: { ja: 'スモーキー', en: 'smoky eye' },
      jp_bold_liner: { ja: 'はっきりライン', en: 'bold liner' },
    },
  },
};

module.exports = { jpLookSpecLexicon };

