const ARCHETYPE_LIBRARY = [
  {
    archetype_id: 'classifier',
    label: 'classifier',
    description: 'Map a user utterance or structured input into a small set of deterministic downstream routes.',
    required_sections: [
      'role/system block',
      'classification task block',
      'allowed labels / enums',
      'confidence contract',
      'entity extraction contract',
      'hard disambiguation rules',
      'missing-data / low-confidence policy',
      'forbidden routing behavior',
      'locale policy',
    ],
    locale_policy: 'Prompt body stays in English. Output labels/enums stay canonical English regardless of locale.',
    example_policy: 'Use 1-2 compact counterexamples only when false-positive routing is a known failure mode.',
    deterministic_notes: 'Downstream thresholding and route mapping stay outside the prompt; prompt must not decide rollout or thresholds.',
  },
  {
    archetype_id: 'structured analyzer / planner',
    label: 'structured analyzer / planner',
    description: 'Turn contextual skincare inputs into schema-bound structured guidance or plan objects.',
    required_sections: [
      'role/system block',
      'task block',
      'output contract block',
      'field semantics block',
      'hard rules block',
      'missing-data policy',
      'forbidden behavior block',
      'locale policy',
      'deterministic post-processing boundary',
    ],
    locale_policy: 'Prompt body stays in English. Localized fields must be explicit and nullable; locale decides whether non-English fields are filled.',
    example_policy: 'Prefer one compact JSON shape example; avoid long few-shot prose.',
    deterministic_notes: 'Prompt owns grounded structure and conservative reasoning. Deterministic code owns hard overrides, quality gates, and remediation.',
  },
  {
    archetype_id: 'strict selector / ranker',
    label: 'strict selector / ranker',
    description: 'Select, rank, or filter candidates under hard grounding constraints.',
    required_sections: [
      'role/system block',
      'selection task block',
      'candidate grounding block',
      'output contract block',
      'hard rules block',
      'ranking priorities',
      'missing-data policy',
      'forbidden behavior block',
      'locale policy',
    ],
    locale_policy: 'Prompt body stays in English. Any localized user-facing strings must be explicitly scoped and optional.',
    example_policy: 'Prefer schema example plus one negative example showing candidate-only grounding.',
    deterministic_notes: 'Prompt must not invent candidates. Deterministic code handles dedupe, guardrails, and link sanitation.',
  },
  {
    archetype_id: 'reviewer / patcher',
    label: 'reviewer / patcher',
    description: 'Review a candidate payload against evidence and patch it without expanding scope.',
    required_sections: [
      'role/system block',
      'review task block',
      'patch output contract',
      'approval / rejection criteria',
      'hard rules block',
      'evidence boundary block',
      'forbidden behavior block',
      'locale policy',
    ],
    locale_policy: 'Prompt body stays in English. Review output should stay canonical and machine-readable.',
    example_policy: 'Use structure-only examples, never content examples that the model could copy verbatim.',
    deterministic_notes: 'Reviewer prompt should never add new evidence; downstream validators still re-run on patched payloads.',
  },
  {
    archetype_id: 'conversational answerer',
    label: 'conversational answerer',
    description: 'Produce concise user-facing answers while optionally attaching lightweight structured hints for follow-up actions.',
    required_sections: [
      'role/system block',
      'answering task block',
      'tone and safety rules',
      'optional structured attachment contract',
      'missing-data policy',
      'forbidden behavior block',
      'locale policy',
      'free-form example policy',
    ],
    locale_policy: 'Prompt body stays in English. locale determines answer language and which optional localized fields are populated.',
    example_policy: 'Use micro-examples only; avoid long stylistic few-shots that dominate answer tone.',
    deterministic_notes: 'Prompt owns answer quality; router / SSE code owns chunking, event ordering, and follow-up action wiring.',
  },
  {
    archetype_id: 'multimodal extractor / report synthesizer',
    label: 'multimodal extractor / report synthesizer',
    description: 'Convert image or multimodal evidence into grounded canonical cosmetic-skin outputs.',
    required_sections: [
      'role/system block',
      'multimodal evidence scope block',
      'output contract block',
      'grounding rules',
      'quality / insufficiency rubric',
      'hard rules block',
      'forbidden behavior block',
      'locale policy',
      'deterministic rendering boundary',
    ],
    locale_policy: 'Prompt body stays in English. Canonical outputs stay English-first unless the contract explicitly asks for localized user text.',
    example_policy: 'Use tiny canonical examples to teach schema and insufficiency behavior, not long descriptive few-shots.',
    deterministic_notes: 'Prompt owns grounded extraction; deterministic code owns semantic validators, safety keyword audits, and renderer localization.',
  },
];

function makeNode(spec) {
  return Object.freeze(spec);
}

const NODE_SPECS = [
  makeNode({
    node_id: 'v2.diagnosis_v2_start_personalized',
    cluster: 'Aurora v2 router + skills',
    runtime_surface: 'Aurora Chat v2',
    call_mode: 'structured_llm',
    entrypoint: 'diagnosis_v2.start',
    consumer: 'DiagnosisStartSkill',
    prompt_source: 'src/auroraBff/services/llm_gateway.js::diagnosis_v2_start_personalized',
    current_version_or_variant: '1.2.0',
    dormant_variants: [],
    provider_path: 'LlmGateway.call -> Gemini structured JSON',
    output_contract: {
      schema: 'DiagnosisStartOutput',
      schema_required: ['follow_up_questions'],
      consumer_required: ['follow_up_questions[]', 'localized question text', 'options[]'],
    },
    goal: 'Ask a short, personalized set of follow-up diagnosis questions without sounding generic or over-medicalized.',
    deterministic_boundary: ['Skill decides card wiring and next_actions.', 'Prompt only proposes follow-up questions and options.'],
    hard_rules: ['Relevance: every question must connect directly to the supplied skin_type or concerns.', 'Non-repetition: do not restate information the user has already provided.', 'Scope: ask skincare intake questions, not medical triage or diagnosis questions.', 'Format: keep every item multiple-choice via options.', 'Brevity: prefer 1-2 high-value questions over filler.'],
    missing_data_policy: ['Use concerns and skin_type when present.', 'If profile is sparse, ask broad but still concrete follow-up questions.'],
    forbidden_behaviors: ['No disease diagnosis.', 'No product recommendations.', 'No long questionnaire dumps.'],
    archetype: 'conversational answerer',
    best_prompt_skeleton: ['Role: concise diagnosis onboarding assistant.', 'Task: ask 2-3 personalized follow-up questions.', 'Output contract: follow_up_questions[] with localized labels and options.', 'Hard rules: short, relevant, non-medical.'],
    locale_policy: 'English prompt body; output question_en/question_zh, localized by locale.',
    example_policy: 'One short example question block is enough.',
    current_eval_assets: ['tests/skills/test_skill_contract.js::gf_diagnosis_start_basic'],
    rewrite_priority: 'P2',
  }),
  makeNode({
    node_id: 'v2.diagnosis_v2_answer_blueprint',
    cluster: 'Aurora v2 router + skills',
    runtime_surface: 'Aurora Chat v2',
    call_mode: 'structured_llm',
    entrypoint: 'diagnosis_v2.answer',
    consumer: 'DiagnosisAnswerSkill',
    prompt_source: 'src/auroraBff/services/llm_gateway.js::diagnosis_v2_answer_blueprint',
    current_version_or_variant: '1.2.0',
    dormant_variants: [],
    provider_path: 'LlmGateway.call -> Gemini structured JSON',
    output_contract: {
      schema: 'DiagnosisBlueprintOutput',
      schema_required: ['blueprint_id', 'inferred_skin_type', 'primary_concerns'],
      consumer_required: ['severity_scores', 'confidence', 'visual_observations|null', 'nudge|null', 'next_recommended_skills[]'],
    },
    goal: 'Synthesize a conservative diagnosis blueprint from goals, profile, logs, and photo availability, without hallucinating visual evidence.',
    deterministic_boundary: ['Skill suppresses visual_analysis when no photo.', 'Prompt still needs to keep visual_observations null/empty when has_photo=false.'],
    hard_rules: ['If has_photo=false, visual_observations must be null or [].', 'Primary concerns must align with goals/profile; max 3.', 'Severity scores must map to primary concerns only.', 'No medical diagnosis language.'],
    missing_data_policy: ['If profile skin type is missing, use "unknown" instead of guessing.', 'If logs are sparse, keep confidence conservative and nudge optional.', 'If no clear nudge exists, return null.'],
    forbidden_behaviors: ['No claims based on unseen photos.', 'No treatment promises.', 'No repeated profile recap in every field.'],
    archetype: 'structured analyzer / planner',
    best_prompt_skeleton: ['Role: evidence-aware skin blueprint planner.', 'Task: infer a diagnosis blueprint from goals/profile/logs/photo availability.', 'Output contract: blueprint JSON with optional visual_observations and nudge.', 'Hard rules: no-photo guardrail, conservative confidence, concern alignment.'],
    locale_policy: 'English prompt body; localized fields only where the schema explicitly allows *_zh or localized nudge text.',
    example_policy: 'Use one compact JSON shape example, not prose examples.',
    current_eval_assets: ['tests/skills/test_skill_contract.js::gf_diagnosis_answer_no_photo', 'tests/aurora_chat_v2_prompt_contract.node.test.cjs'],
    rewrite_priority: 'P0',
  }),
  makeNode({
    node_id: 'v2.routine_categorize_products',
    cluster: 'Aurora v2 router + skills',
    runtime_surface: 'Aurora Chat v2',
    call_mode: 'structured_llm',
    entrypoint: 'routine.intake_products',
    consumer: 'RoutineIntakeProductsSkill',
    prompt_source: 'src/auroraBff/services/llm_gateway.js::routine_categorize_products',
    current_version_or_variant: '1.2.0',
    dormant_variants: [],
    provider_path: 'LlmGateway.call -> Gemini structured JSON',
    output_contract: {
      schema: 'ProductCategorizationOutput',
      schema_required: ['categorized_products'],
      consumer_required: ['step assignment', 'dedupe-safe categorization'],
    },
    goal: 'Categorize user-provided products into routine steps without over-classifying unknown items.',
    deterministic_boundary: ['Skill handles routine card shaping.', 'Prompt only assigns categories and reasons.'],
    hard_rules: ['Conservative-classification: if the role is unclear, put the item in unresolved instead of forcing a step.', 'Dedupe: do not duplicate the same product across conflicting step assignments.', 'Brand: do not guess a brand or a full resolved name beyond the supplied text.', 'Sunscreen: if SPF or sunscreen is explicit, assign step_assignment="sunscreen", time_of_day="am", and include SUNSCREEN concept.', 'Retinoid: if retinoid or retinal is explicit, keep the classification conservative and avoid implying AM use.', 'Scope: do not recommend new products, optimize the routine, or make efficacy promises.'],
    missing_data_policy: ['If the product function is unclear, categorize as other/unknown instead of guessing.', 'Return empty arrays rather than fabricating categories.'],
    forbidden_behaviors: ['No new products.', 'No efficacy promises.', 'No routine optimization advice.'],
    archetype: 'structured analyzer / planner',
    best_prompt_skeleton: ['Role: routine intake classifier.', 'Task: assign products to routine steps.', 'Output contract: categorized_products[].', 'Hard rules: conservative categorization and dedupe.'],
    locale_policy: 'English prompt body; localized text only when explicitly requested by the schema.',
    example_policy: 'Prefer one compact array example.',
    current_eval_assets: ['tests/aurora_bff_skills_orchestrator.node.test.cjs'],
    rewrite_priority: 'P2',
  }),
  makeNode({
    node_id: 'v2.routine_audit_optimize',
    cluster: 'Aurora v2 router + skills',
    runtime_surface: 'Aurora Chat v2',
    call_mode: 'structured_llm',
    entrypoint: 'routine.audit_optimize',
    consumer: 'RoutineAuditOptimizeSkill',
    prompt_source: 'src/auroraBff/services/llm_gateway.js::routine_audit_optimize',
    current_version_or_variant: '1.2.0',
    dormant_variants: [],
    provider_path: 'LlmGateway.call -> Gemini structured JSON',
    output_contract: {
      schema: 'RoutineAuditOutput',
      schema_required: ['changes', 'compatibility_issues'],
      consumer_required: ['optimized_am_steps', 'optimized_pm_steps'],
    },
    goal: 'Translate deterministic audit findings and user context into a safer, simpler optimized routine.',
    deterministic_boundary: ['Deterministic audit precomputes SPF/retinoid/interaction issues.', 'Prompt should propose optimized steps and human-readable change rationale, not override audit facts.'],
    hard_rules: ['Safety fixes beat cosmetic optimization.', 'Respect pregnancy / barrier / sensitivity flags.', 'If routine data is incomplete, prefer minimal safe edits over elaborate rewrites.'],
    missing_data_policy: ['If a step cannot be confidently optimized, keep the original step shape.', 'If compatibility issues are unclear, return them conservatively rather than inventing new conflicts.'],
    forbidden_behaviors: ['No aggressive escalation of actives.', 'No replacing products with invented items.', 'No contradicting deterministic safety fixes.'],
    archetype: 'structured analyzer / planner',
    best_prompt_skeleton: ['Role: conservative routine auditor.', 'Task: optimize routine using deterministic audit findings.', 'Output contract: optimized steps, changes, compatibility issues.', 'Hard rules: safety-first and no fabricated replacements.'],
    locale_policy: 'English prompt body; localized user-facing text only when the schema allows it.',
    example_policy: 'One compact before/after JSON example is sufficient.',
    current_eval_assets: ['tests/skills/test_skill_contract.js::gf_post_procedure_recovery', 'tests/aurora_bff_routine_multiturn_contract_v2.node.test.cjs'],
    rewrite_priority: 'P0',
  }),
  makeNode({
    node_id: 'v2.reco_step_based',
    cluster: 'Aurora v2 router + skills',
    runtime_surface: 'Aurora Chat v2',
    call_mode: 'structured_llm',
    entrypoint: 'reco.step_based',
    consumer: 'RecoStepBasedSkill',
    prompt_source: 'src/auroraBff/services/llm_gateway.js::reco_step_based',
    current_version_or_variant: '1.2.0',
    dormant_variants: [],
    provider_path: 'LlmGateway.call -> Gemini structured JSON',
    output_contract: {
      schema: 'StepRecommendationOutput',
      schema_required: ['step_recommendations'],
      consumer_required: ['reasoning per recommendation', 'next_actions-compatible recommendation shape'],
    },
    goal: 'Recommend products or steps from context with concern/ingredient awareness and graceful empty-state behavior.',
    deterministic_boundary: ['Skill and quality gates sanitize candidate pools and next_actions.', 'Prompt should rank and justify recommendations only from supplied context.'],
    hard_rules: ['If evidence or candidates are weak, return fewer items.', 'Respect target_ingredient and concerns when present.', 'Avoid stale "start tracking" style calls to action in recommendation content.'],
    missing_data_policy: ['When profile/routine is sparse, stay concern-first and conservative.', 'If no good match exists, return an explainable empty result.'],
    forbidden_behaviors: ['No invented catalog products.', 'No hard claims without support.', 'No dumping generic routines when asked for product picks.'],
    archetype: 'structured analyzer / planner',
    best_prompt_skeleton: ['Role: recommendation planner.', 'Task: produce step-based recommendations from supplied context.', 'Output contract: step_recommendations[].', 'Hard rules: groundedness, empty-state behavior, concern/ingredient fidelity.'],
    locale_policy: 'English prompt body; localized user-facing text only where the schema allows.',
    example_policy: 'Use one compact recommendation array example.',
    current_eval_assets: ['tests/aurora_chat_v2_routes.node.test.cjs', 'tests/skills/test_skill_contract.js::gf_dupe_suggest_no_candidates'],
    rewrite_priority: 'P1',
  }),
  makeNode({
    node_id: 'v2.tracker_checkin_insights',
    cluster: 'Aurora v2 router + skills',
    runtime_surface: 'Aurora Chat v2',
    call_mode: 'structured_llm',
    entrypoint: 'tracker.checkin_insights',
    consumer: 'TrackerCheckinInsightsSkill',
    prompt_source: 'src/auroraBff/services/llm_gateway.js::tracker_checkin_insights',
    current_version_or_variant: '1.2.0',
    dormant_variants: [],
    provider_path: 'LlmGateway.call -> Gemini structured JSON',
    output_contract: {
      schema: 'CheckinInsightsOutput',
      schema_required: ['trend_summary', 'suggested_action'],
      consumer_required: ['sensation_trend', 'days_tracked', 'attribution|null', 'detailed_review|null'],
    },
    goal: 'Summarize check-in trends and next actions conservatively, especially when there are no photos.',
    deterministic_boundary: ['Skill validator blocks visual references when no photos exist.', 'Prompt should already avoid photo-grounded wording unless has_photo=true.'],
    hard_rules: ['If has_photo=false, do not describe visible changes.', 'Trend summaries must stay grounded in logs, not imagined progress.', 'Suggested action must be one the skill knows how to route.'],
    missing_data_policy: ['If attribution is weak, use uncertain attribution or null.', 'If logs are noisy, keep the summary cautious and short.'],
    forbidden_behaviors: ['No visual claims without photos.', 'No fabricated causal certainty.', 'No judgmental tone.'],
    archetype: 'structured analyzer / planner',
    best_prompt_skeleton: ['Role: progress insights analyst.', 'Task: summarize check-in trends and suggest the next best action.', 'Output contract: trend_summary, attribution, detailed_review, suggested_action.', 'Hard rules: no-photo guardrail and conservative causality.'],
    locale_policy: 'English prompt body; output localized text only when explicitly allowed.',
    example_policy: 'Use one short structured output example.',
    current_eval_assets: ['tests/skills/test_skill_contract.js::gf_checkin_insights_no_photo'],
    rewrite_priority: 'P0',
  }),
  makeNode({
    node_id: 'v2.product_analyze',
    cluster: 'Aurora v2 router + skills',
    runtime_surface: 'Aurora Chat v2',
    call_mode: 'structured_llm',
    entrypoint: 'product.analyze',
    consumer: 'ProductAnalyzeSkill',
    prompt_source: 'src/auroraBff/services/llm_gateway.js::product_analyze',
    current_version_or_variant: '1.2.0',
    dormant_variants: [],
    provider_path: 'LlmGateway.call -> Gemini structured JSON',
    output_contract: {
      schema: 'ProductAnalysisOutput',
      schema_required: ['product_name', 'product_type', 'suitability', 'usage'],
      consumer_required: ['brand|null', 'has_spf', 'key_ingredients[]', 'risk_flags[]'],
    },
    goal: 'Provide a grounded product suitability verdict and usage guidance that deterministic safety rules can safely refine.',
    deterministic_boundary: ['Deterministic layer enforces SPF, retinoid, pregnancy, and high-acid hard overrides.', 'Prompt should still return a coherent baseline usage object and grounded risk flags.'],
    hard_rules: ['SPF/sunscreen: usage.time_of_day MUST be "am".', 'SPF/sunscreen: usage.frequency MUST be "daily".', 'SPF/sunscreen: usage.reapply MUST include outdoor reapplication guidance.', 'SPF/sunscreen: NEVER suggest "pm", "2-3x/week", or "every other day" for sunscreen.', 'Retinoid: prefer pm-only framing and conservative onboarding frequency.', 'Pregnancy: if safety_flags indicate pregnancy and product contains retinoids, include a blocking risk flag.', 'Unknown-ingredient: do not fabricate key ingredients when ingredient_list is weak or missing.', 'Evidence: when uncertainty is high, keep the verdict cautious rather than assertive.'],
    missing_data_policy: ['Use null or [] for unknown ingredient facts.', 'Keep verdict cautious when formulation evidence is incomplete.'],
    forbidden_behaviors: ['No brand hallucination.', 'No concentration guessing.', 'No PM-first sunscreen guidance.'],
    archetype: 'structured analyzer / planner',
    best_prompt_skeleton: ['Role: objective product analyst.', 'Task: analyze product suitability from anchor + ingredient context.', 'Output contract: product verdict JSON.', 'Hard rules: SPF / retinoid / pregnancy / uncertainty.'],
    locale_policy: 'English prompt body; *_zh fields only when locale justifies them.',
    example_policy: 'One compact JSON example is enough.',
    current_eval_assets: ['tests/skills/test_skill_contract.js::gf_product_analyze_spf', 'tests/aurora_chat_v2_prompt_contract.node.test.cjs'],
    rewrite_priority: 'P0',
  }),
  makeNode({
    node_id: 'v2.ingredient_report',
    cluster: 'Aurora v2 router + skills',
    runtime_surface: 'Aurora Chat v2',
    call_mode: 'structured_llm',
    entrypoint: 'ingredient.report',
    consumer: 'IngredientReportSkill._handleSpecificIngredient',
    prompt_source: 'src/auroraBff/services/llm_gateway.js::ingredient_report',
    current_version_or_variant: '2.2.0',
    dormant_variants: [],
    provider_path: 'LlmGateway.call -> Gemini structured JSON',
    output_contract: {
      schema: 'IngredientReportOutput',
      schema_required: ['ingredient_name', 'claims'],
      consumer_required: ['inci_name|null', 'category', 'description_en', 'benefits[]', 'how_to_use|null', 'watchouts[]', 'interactions[]', 'related_ingredients[]'],
    },
    goal: 'Generate a conservative ingredient report that always contains ingredient-level claims and never turns uncertainty into product marketing.',
    deterministic_boundary: ['Skill injects a cautious ingredient_claims section when claims are empty.', 'Prompt should still return well-formed claims and watchouts whenever possible.'],
    hard_rules: ['Unknown or unverified ingredients must not be framed as confirmed facts.', 'Claims must stay ingredient-level only.', 'Every claim needs an evidence badge.'],
    missing_data_policy: ['If ontology is missing, keep claims generic and uncertain.', 'If INCI is unknown, return null instead of guessing.'],
    forbidden_behaviors: ['No "products containing X".', 'No branded examples.', 'No medical certainty.'],
    archetype: 'structured analyzer / planner',
    best_prompt_skeleton: ['Role: evidence-aware ingredient analyst.', 'Task: produce a structured ingredient report.', 'Output contract: overview, benefits, claims, usage, watchouts, interactions.', 'Hard rules: uncertain evidence and no productization.'],
    locale_policy: 'English prompt body; description_zh/text_zh may be null when locale is not Chinese.',
    example_policy: 'One short JSON example is enough.',
    current_eval_assets: ['tests/skills/test_skill_contract.js::gf_ingredient_unverified', 'tests/aurora_chat_v2_skill_guards.node.test.cjs', 'tests/aurora_chat_v2_prompt_contract.node.test.cjs'],
    rewrite_priority: 'P0',
  }),
  makeNode({
    node_id: 'v2.ingredient_query_answer',
    cluster: 'Aurora v2 router + skills',
    runtime_surface: 'Aurora Chat v2',
    call_mode: 'structured_llm',
    entrypoint: 'ingredient.report::_handleIngredientQuestion',
    consumer: 'IngredientReportSkill._handleIngredientQuestion',
    prompt_source: 'src/auroraBff/services/llm_gateway.js::ingredient_query_answer',
    current_version_or_variant: '1.2.0',
    dormant_variants: [],
    provider_path: 'LlmGateway.call -> Gemini structured JSON',
    output_contract: {
      schema: 'IngredientQueryOutput',
      schema_required: ['answer_en', 'ingredients_mentioned'],
      consumer_required: ['answer_zh|null', 'safety_notes[]', 'followup_suggestions[]|optional'],
    },
    goal: 'Answer open ingredient questions directly while optionally surfacing a short ingredient list for follow-up exploration.',
    deterministic_boundary: ['Skill maps ingredients_mentioned into cards and next_actions.', 'Prompt must keep the answer concise and the ingredient list grounded.'],
    hard_rules: ['Answer the asked question before listing ingredients.', 'If safety_notes are relevant, include them succinctly.', 'Do not overstate evidence.'],
    missing_data_policy: ['If evidence is weak, say so briefly and stay useful.', 'If no ingredients fit, return an empty list rather than guessing.'],
    forbidden_behaviors: ['No product marketing.', 'No unnecessary long essay.', 'No medical diagnosis language.'],
    archetype: 'conversational answerer',
    best_prompt_skeleton: ['Role: concise ingredient educator.', 'Task: answer the user question and optionally attach ingredient mentions.', 'Output contract: answer + safety notes + ingredients_mentioned.', 'Hard rules: directness, caution, no marketing.'],
    locale_policy: 'English prompt body; answer_zh only when locale is zh-CN.',
    example_policy: 'Use micro examples only.',
    current_eval_assets: ['tests/aurora_chat_v2_routes.node.test.cjs'],
    rewrite_priority: 'P1',
  }),
  makeNode({
    node_id: 'v2.intent_classifier',
    cluster: 'Aurora v2 router + skills',
    runtime_surface: 'Aurora Chat v2',
    call_mode: 'structured_llm',
    entrypoint: 'skill_router._classifyIntent',
    consumer: 'SkillRouter',
    prompt_source: 'src/auroraBff/services/llm_gateway.js::intent_classifier',
    current_version_or_variant: '1.2.0',
    dormant_variants: [],
    provider_path: 'LlmGateway.call -> Gemini structured JSON',
    output_contract: {
      schema: 'IntentClassifierOutput',
      schema_required: ['intent', 'confidence', 'entities'],
      consumer_required: ['entities.ingredients[]', 'entities.products[]', 'entities.concerns[]', 'entities.user_question'],
    },
    goal: 'Classify a skincare message into the right Aurora skill intent and extract lightweight entities for routing.',
    deterministic_boundary: ['Router owns confidence threshold, intent-to-skill mapping, and fallback to freeform.', 'Prompt only classifies and extracts entities.'],
    hard_rules: ['Conservative-routing: if the message is broad or ambiguous, prefer general_chat or routine_advice.', 'Ingredient-query vs ingredient_report: open questions use ingredient_query, direct lookups use ingredient_report.', 'Product-analysis: use only when the user asks to analyze a specific product.', 'Recommendation: use recommend_products only for clear product requests, not education.', 'Entity: do not invent entities not explicit in the user message.', 'Confidence: keep below 0.5 when routing is weak enough that freeform fallback is safer.'],
    missing_data_policy: ['If uncertain, lower confidence instead of guessing a strong intent.', 'Use empty arrays / null entities rather than fabricating them.'],
    forbidden_behaviors: ['No direct policy decisions.', 'No invented product names or ingredients.', 'No overconfident routing.'],
    archetype: 'classifier',
    best_prompt_skeleton: ['Role: route classifier.', 'Task: map user message to intent + confidence + entities.', 'Output contract: strict intent JSON.', 'Hard rules: conservative confidence and entity extraction.'],
    locale_policy: 'English prompt body; intent labels and entity keys remain canonical English.',
    example_policy: 'Use 1-2 tricky routing counterexamples.',
    current_eval_assets: ['tests/aurora_chat_v2_routes.node.test.cjs'],
    rewrite_priority: 'P1',
  }),
  makeNode({
    node_id: 'v2.dupe_suggest',
    cluster: 'Aurora v2 router + skills',
    runtime_surface: 'Aurora Chat v2',
    call_mode: 'structured_llm',
    entrypoint: 'dupe.suggest',
    consumer: 'DupeSuggestSkill',
    prompt_source: 'src/auroraBff/services/llm_gateway.js::dupe_suggest',
    current_version_or_variant: '2.1.0',
    dormant_variants: [],
    provider_path: 'LlmGateway.call -> Gemini structured JSON',
    output_contract: {
      schema: 'DupeSuggestOutput',
      schema_required: ['anchor_summary', 'candidates'],
      consumer_required: ['tradeoffs', 'empty_state-safe behavior'],
    },
    goal: 'Suggest plausible dupes from a provided candidate pool without fabricating similarity claims.',
    deterministic_boundary: ['Preconditions and quality gates own empty-state behavior.', 'Prompt should compare only the supplied candidates.'],
    hard_rules: ['Candidate-pool-only: never invent or introduce a product not in candidates.', 'Empty-pool: if candidates is empty, return candidates=[].', 'Fairness: do not describe any candidate as an exact duplicate or identical formula.', 'Tradeoff: every returned candidate must include at least one concrete difference and one concrete tradeoff.', 'Ranking: prefer fewer, more plausible dupes over a long weak list.', 'Tone: keep comparison language factual, non-marketing, and profile-aware.'],
    missing_data_policy: ['Prefer fewer candidates when signal is weak.', 'Keep anchor summary short and concrete.'],
    forbidden_behaviors: ['No fabricated equivalence claims.', 'No shopping hype.', 'No hidden candidate invention.'],
    archetype: 'structured analyzer / planner',
    best_prompt_skeleton: ['Role: dupe selector.', 'Task: rank supplied candidates against an anchor.', 'Output contract: anchor_summary + candidates[].', 'Hard rules: candidate-only grounding and empty-state safety.'],
    locale_policy: 'English prompt body; localized text only when supported by the schema.',
    example_policy: 'Prefer one compact ranking example.',
    current_eval_assets: ['tests/skills/test_skill_contract.js::gf_dupe_suggest_no_candidates'],
    rewrite_priority: 'P2',
  }),
  makeNode({
    node_id: 'v2.dupe_compare',
    cluster: 'Aurora v2 router + skills',
    runtime_surface: 'Aurora Chat v2',
    call_mode: 'structured_llm',
    entrypoint: 'dupe.compare',
    consumer: 'DupeCompareSkill',
    prompt_source: 'src/auroraBff/services/llm_gateway.js::dupe_compare',
    current_version_or_variant: '1.2.0',
    dormant_variants: [],
    provider_path: 'LlmGateway.call -> Gemini structured JSON',
    output_contract: {
      schema: 'DupeCompareOutput',
      schema_required: ['anchor_summary', 'comparisons'],
      consumer_required: ['fair tradeoff framing', 'comparison-safe reasoning'],
    },
    goal: 'Compare an anchor product against supplied targets fairly and concretely.',
    deterministic_boundary: ['Skill renders the compare card; prompt should only compare supplied items.'],
    hard_rules: ['Grounding: compare only the supplied anchor and targets; do not invent extra products or ingredient decks.', 'Tradeoff: each comparison must surface a real difference or uncertainty, not just generic praise.', 'Fairness: do not claim two formulas are identical or guaranteed substitutes unless explicitly supported.', 'Completeness: every comparison must include key_ingredients_match, texture_comparison, suitability_comparison, price_comparison, and verdict.', 'Uncertainty: when evidence is thin, keep scores conservative and state what remains uncertain.'],
    missing_data_policy: ['If evidence is thin, say which comparison fields are uncertain.', 'Return fewer comparison bullets rather than vague filler.'],
    forbidden_behaviors: ['No fabricated benefits.', 'No marketing language.', 'No unsupported "identical formula" claims.'],
    archetype: 'structured analyzer / planner',
    best_prompt_skeleton: ['Role: fair comparator.', 'Task: compare anchor and targets.', 'Output contract: anchor_summary + comparisons[].', 'Hard rules: tradeoffs and groundedness.'],
    locale_policy: 'English prompt body; localized text only where the schema supports it.',
    example_policy: 'One compact comparison example is enough.',
    current_eval_assets: ['tests/aurora_bff_product_intel.test.js'],
    rewrite_priority: 'P2',
  }),
  makeNode({
    node_id: 'v2.travel_apply_mode',
    cluster: 'Aurora v2 router + skills',
    runtime_surface: 'Aurora Chat v2',
    call_mode: 'structured_llm',
    entrypoint: 'travel.apply_mode',
    consumer: 'TravelApplyModeSkill',
    prompt_source: 'src/auroraBff/services/llm_gateway.js::travel_apply_mode',
    current_version_or_variant: '1.2.0',
    dormant_variants: [],
    provider_path: 'LlmGateway.call -> Gemini structured JSON',
    output_contract: {
      schema: 'TravelModeOutput',
      schema_required: ['uv_level', 'humidity'],
      consumer_required: ['reduce_irritation', 'packing_list[]', 'inferred_climate|null'],
    },
    goal: 'Translate travel conditions into a safe travel-mode adjustment object with strong UV and irritation safeguards.',
    deterministic_boundary: ['Skill deterministically adds reduce_actives when high UV overlaps with strong actives or sensitivity.', 'Prompt should still set reduce_irritation correctly when evidence is clear.'],
    hard_rules: ['High UV must trigger SPF-minded guidance.', 'Strong actives or sensitivity flags should set reduce_irritation=true.', 'Packing list should stay practical.'],
    missing_data_policy: ['If destination certainty is low, use the archetype conservatively.', 'If humidity is unclear, default to medium instead of guessing extreme values.'],
    forbidden_behaviors: ['No weather hallucination.', 'No aggressive treatment escalation during travel.', 'No omission of reduce_irritation.'],
    archetype: 'structured analyzer / planner',
    best_prompt_skeleton: ['Role: travel routine planner.', 'Task: infer travel conditions and adjustments.', 'Output contract: uv_level, humidity, reduce_irritation, packing_list, inferred_climate.', 'Hard rules: high UV, active reduction, practical packing.'],
    locale_policy: 'English prompt body; packing reasons can include localized text only when schema allows.',
    example_policy: 'One compact travel JSON example is enough.',
    current_eval_assets: ['tests/skills/test_skill_contract.js::gf_travel_high_uv', 'tests/aurora_chat_v2_skill_guards.node.test.cjs', 'tests/aurora_chat_v2_prompt_contract.node.test.cjs'],
    rewrite_priority: 'P0',
  }),
  makeNode({
    node_id: 'v2.chat.freeform',
    cluster: 'Aurora v2 router + skills',
    runtime_surface: 'Aurora Chat v2',
    call_mode: 'freeform_chat',
    entrypoint: 'skill_router._handleFreeFormChat',
    consumer: 'SkillRouter',
    prompt_source: 'src/auroraBff/services/llm_gateway.js::buildFreeformChatSystemPrompt + chat()',
    current_version_or_variant: 'inline_system_prompt_v2',
    dormant_variants: [],
    provider_path: 'LlmGateway.chat -> Gemini chat -> SSE chunk/result adapter',
    output_contract: {
      schema: null,
      schema_required: [],
      consumer_required: ['text answer', 'optional ingredients_mentioned[]', 'optional safety_notes[]', 'optional followup_suggestions[]'],
    },
    goal: 'Answer unresolved skincare chat questions helpfully and safely while remaining compatible with SSE chunk/result behavior.',
    deterministic_boundary: ['Router owns SSE event ordering and next_action mapping.', 'Prompt owns final answer quality and optional lightweight structure.'],
    hard_rules: ['Answer directly before suggesting follow-ups.', 'Respect safety wording.', 'If ingredient mentions are included, keep them grounded and sparse.'],
    missing_data_policy: ['State uncertainty plainly when needed.', 'If structured extras are not needed, omit them instead of padding.'],
    forbidden_behaviors: ['No over-medicalized claims.', 'No fake confidence.', 'No mismatch between streamed chunks and final answer intent.'],
    archetype: 'conversational answerer',
    best_prompt_skeleton: ['Role: evidence-aware skincare advisor.', 'Task: answer the user directly and optionally attach lightweight structured hints.', 'Hard rules: safety, caution, SSE-consistent tone.'],
    locale_policy: 'English system prompt body; final answer language follows locale.',
    example_policy: 'No long few-shot examples; preserve flexible conversation tone.',
    current_eval_assets: ['tests/aurora_chat_v2_routes.node.test.cjs'],
    rewrite_priority: 'P1',
  }),
  makeNode({
    node_id: 'legacy.diagnosis_gate.prompt',
    cluster: 'legacy diagnosis / gating',
    runtime_surface: 'legacy Node chat routes',
    call_mode: 'deterministic_gate_prompt',
    entrypoint: 'buildDiagnosisPrompt',
    consumer: 'legacy /v1/chat diagnosis gate',
    prompt_source: 'src/auroraBff/gating.js::buildDiagnosisPrompt',
    current_version_or_variant: 'diagnosis_gate_prompt_v2',
    dormant_variants: [],
    provider_path: 'none (deterministic gate prompt)',
    output_contract: {
      schema: null,
      schema_required: [],
      consumer_required: ['single gate prompt string', 'compatible with diagnosis chips'],
    },
    goal: 'Collect the next missing profile field with minimum friction before unlocking recommendation flows.',
    deterministic_boundary: ['All routing, missing-field ordering, and chips stay deterministic.', 'This node is tracked because its wording affects gate completion quality.'],
    hard_rules: ['Ask only the current missing field.', 'Keep the gate brief.', 'Do not ask product or medical questions.'],
    missing_data_policy: ['If current field metadata is missing, fall back to the generic prefix.'],
    forbidden_behaviors: ['No long explanation.', 'No guilt language.', 'No unlocking recommendations prematurely.'],
    archetype: 'conversational answerer',
    best_prompt_skeleton: ['Role: concise gate prompt.', 'Task: ask for one missing profile field only.', 'Hard rules: brief, non-judgmental, deterministic.'],
    locale_policy: 'Prompt copy localizes fully by request language.',
    example_policy: 'No examples needed; this is deterministic copy.',
    current_eval_assets: ['tests/aurora_legacy_gate_prompt_contract.node.test.cjs', 'tests/aurora_bff.node.test.cjs', 'tests/aurora_bff_chat_v2_policy.node.test.cjs'],
    rewrite_priority: 'P2',
  }),
  makeNode({
    node_id: 'legacy.fit_check.anchor_gate',
    cluster: 'legacy diagnosis / gating',
    runtime_surface: 'legacy Node fit-check routes',
    call_mode: 'deterministic_gate_prompt',
    entrypoint: 'buildFitCheckAnchorPrompt',
    consumer: 'legacy fit-check anchor collection',
    prompt_source: 'src/auroraBff/routes.js::buildFitCheckAnchorPrompt',
    current_version_or_variant: 'fit_check_anchor_gate_v2',
    dormant_variants: [],
    provider_path: 'none (deterministic gate prompt)',
    output_contract: {
      schema: null,
      schema_required: [],
      consumer_required: ['anchor request text', 'chips for name/link/INCI'],
    },
    goal: 'Request a concrete product anchor before product-fit analysis without confusing the user about what qualifies as an anchor.',
    deterministic_boundary: ['Parsing and anchor validation stay deterministic.', 'This node only supplies wording and chips.'],
    hard_rules: ['Ask for link, full name, or INCI only.', 'Do not begin analysis before an anchor exists.', 'Stay actionable.'],
    missing_data_policy: ['If the route lacks anchor data, use the generic anchor request prompt.'],
    forbidden_behaviors: ['No pseudo-analysis.', 'No vague "tell me more" copy.', 'No brand guessing.'],
    archetype: 'conversational answerer',
    best_prompt_skeleton: ['Role: anchor collection gate.', 'Task: request one of link/name/INCI.', 'Hard rules: brief, concrete, non-analytical.'],
    locale_policy: 'Fully localized deterministic copy.',
    example_policy: 'No examples needed.',
    current_eval_assets: ['tests/aurora_legacy_gate_prompt_contract.node.test.cjs', 'tests/aurora_bff.node.test.cjs', 'tests/cases_shopping_focus.jsonl'],
    rewrite_priority: 'P2',
  }),
  makeNode({
    node_id: 'legacy.skin.vision_mainline',
    cluster: 'legacy skin analysis',
    runtime_surface: '/v1/analysis/skin mainline',
    call_mode: 'multimodal_llm',
    entrypoint: 'buildSkinVisionPromptBundle -> runGeminiVisionStrategy',
    consumer: 'skinLlmGateway vision layer',
    prompt_source: 'src/auroraBff/skinLlmPrompts.js::buildSkinVisionPromptBundle',
    current_version_or_variant: 'skin_report_v2_hardened',
    dormant_variants: ['skin_vision_v3_canonical'],
    provider_path: 'skinLlmGateway.runGeminiVisionStrategy -> Gemini multimodal JSON',
    output_contract: {
      schema: 'SkinVisionCanonicalSchema or legacy observation JSON',
      schema_required: ['visibility status / observations', 'quality-aware insufficiency signaling'],
      consumer_required: ['grounded cue extraction only', 'quality_note / limits behavior'],
    },
    goal: 'Extract only grounded visible skin cues from photos and explicitly distinguish sufficient, limited, and insufficient evidence.',
    deterministic_boundary: ['Photo quality classification and semantic validation stay deterministic.', 'Prompt owns grounded cue extraction only.'],
    hard_rules: ['No product advice.', 'No medical diagnosis.', 'If evidence is insufficient, say so structurally and keep observations empty/minimal.'],
    missing_data_policy: ['Low-quality photos should trigger insufficient/limited outputs, not guessed cues.', 'Use canonical enums only.'],
    forbidden_behaviors: ['No routines.', 'No brands.', 'No disease labels.'],
    archetype: 'multimodal extractor / report synthesizer',
    best_prompt_skeleton: ['Role: cosmetic skin cue extractor.', 'Task: extract grounded cues from the face photo only.', 'Output contract: canonical observation JSON.', 'Hard rules: insufficiency rubric and no advice.'],
    locale_policy: 'English-first canonical outputs; localization happens later in rendering.',
    example_policy: 'Use tiny canonical examples for sufficient vs insufficient cases.',
    current_eval_assets: [
      'tests/aurora_bff_skin_prompt_v3.node.test.cjs',
      'tests/aurora_bff_vision_policy.node.test.cjs',
      'tests/aurora_bff_photo_full_chain_e2e.node.test.cjs',
      'tests/aurora_legacy_skin_prompt_contract.node.test.cjs',
    ],
    rewrite_priority: 'P1',
  }),
  makeNode({
    node_id: 'legacy.skin.report_mainline',
    cluster: 'legacy skin analysis',
    runtime_surface: '/v1/analysis/skin mainline',
    call_mode: 'structured_llm',
    entrypoint: 'buildSkinReportPromptBundle -> runGeminiReportStrategy',
    consumer: 'skinLlmGateway report layer',
    prompt_source: 'src/auroraBff/skinLlmPrompts.js::buildSkinReportPromptBundle',
    current_version_or_variant: 'skin_report_v3_hardened',
    dormant_variants: ['skin_report_v2_hardened', 'skin_report_v3_canonical'],
    provider_path: 'skinLlmGateway.runGeminiReportStrategy -> Gemini structured JSON',
    output_contract: {
      schema: 'SkinReportCanonicalSchema or legacy report strategy JSON',
      schema_required: ['strategy', 'primary_question', 'routine_expert', 'guidance_brief'],
      consumer_required: ['findings[]', 'two_week_focus[]', 'next_step_options[]'],
    },
    goal: 'Transform deterministic signals and optional visual cues into a conservative, structured cosmetic skincare plan.',
    deterministic_boundary: ['Routes and validators normalize findings, confidence, and rendering.', 'Prompt owns plan synthesis, not product recommendation.'],
    hard_rules: ['Separation: do not repeat vision observations verbatim; reference by cue name only.', 'Skin-type: user-selected skin type is a prior, not ground truth; compare against observed cues.', 'Cue-linking: each routine step must reference at least 1 observed cue.', 'Safety: non-medical guidance only; for risk terms give light caution + conservative plan.', 'Quality: quality-related information must never appear inside findings.'],
    missing_data_policy: ['If cues are weak, keep strategy conservative and explicitly limited.', 'Do not invent detailed routine history, products, brands, or high-confidence conclusions.'],
    forbidden_behaviors: ['No disease diagnoses, treatment claims, or prescription drug names.', 'No brand or specific product recommendations.', 'No generic template talk or repeated disclaimers.', 'No unsupported confidence escalation.'],
    archetype: 'multimodal extractor / report synthesizer',
    best_prompt_skeleton: ['Role: conservative report synthesizer.', 'Task: turn signals into a structured plan.', 'Output contract: strategy JSON with findings, routine_expert, two_week_focus, next_step_options.', 'Hard rules: separation, cue-linking, safety, quality.'],
    locale_policy: 'English-first canonical output even when downstream renderer localizes later.',
    example_policy: 'Use compact schema-first examples only.',
    current_eval_assets: [
      'tests/aurora_bff_skin_prompt_v3.node.test.cjs',
      'tests/aurora_bff_vision_policy.node.test.cjs',
      'tests/aurora_bff_photo_full_chain_e2e.node.test.cjs',
      'tests/aurora_legacy_skin_prompt_contract.node.test.cjs',
    ],
    rewrite_priority: 'P0',
  }),
  makeNode({
    node_id: 'legacy.skin.deepening_mainline',
    cluster: 'legacy skin analysis',
    runtime_surface: '/v1/analysis/skin deepening',
    call_mode: 'structured_llm',
    entrypoint: 'buildSkinDeepeningPromptBundle -> runGeminiDeepeningStrategy',
    consumer: 'skinLlmGateway deepening layer',
    prompt_source: 'src/auroraBff/skinLlmPrompts.js::buildSkinDeepeningPromptBundle',
    current_version_or_variant: 'skin_deepening_v2_hardened',
    dormant_variants: ['skin_deepening_v1_hardened', 'skin_deepening_v2_canonical'],
    provider_path: 'skinLlmGateway.runGeminiDeepeningStrategy -> Gemini structured JSON',
    output_contract: {
      schema: 'SkinDeepeningCanonicalSchema or legacy deepening JSON',
      schema_required: ['narrative', 'reasoning', 'deepening_question', 'deepening_options'],
      consumer_required: ['narrative / reasoning', 'deepening_question', 'deepening_options'],
    },
    goal: 'Pick the correct deepening phase and next question so the skin analysis flow advances without redundant or mistimed asks.',
    deterministic_boundary: ['Phase planning and renderer behavior stay deterministic around the model output.', 'Prompt chooses phase/question content within canonical limits.'],
    hard_rules: ['Phase-fidelity: reasoning and deepening_question must stay appropriate for the current phase.', 'Matching: deepening_question and deepening_options must be logically consistent.', 'Safety: no disease diagnosis, no prescription drug names, no treatment claims.', 'Grounding: every narrative sentence must reference a specific profile attribute.', 'Actionability: map reactions to concrete routine adjustments.'],
    missing_data_policy: ['If context is weak, stay conservative and ask the next best question.', 'Do not pretend to know routine history, reaction history, or photo details.'],
    forbidden_behaviors: ['No brand or specific product recommendations.', 'No disease framing or prescription references.', 'No long generic pep-talks or template filler.'],
    archetype: 'multimodal extractor / report synthesizer',
    best_prompt_skeleton: ['Role: warm, professional deepening advisor.', 'Task: generate personalized deepening narrative for current phase.', 'Output contract: narrative/reasoning/deepening_question/deepening_options JSON.', 'Hard rules: phase-fidelity, matching, safety, grounding.'],
    locale_policy: 'English-first canonical output; localized rendering occurs downstream.',
    example_policy: 'Use tiny phase-selection examples only.',
    current_eval_assets: [
      'tests/aurora_bff_skin_deepening.node.test.cjs',
      'tests/aurora_bff_skin_prompt_v3.node.test.cjs',
      'tests/aurora_legacy_skin_prompt_contract.node.test.cjs',
    ],
    rewrite_priority: 'P1',
  }),
  makeNode({
    node_id: 'legacy.product_intel.deep_scan',
    cluster: 'legacy product intel / fit check',
    runtime_surface: 'legacy fit-check + routine autoscan',
    call_mode: 'upstream_prompt',
    entrypoint: 'buildProductDeepScanPrompt -> auroraChat',
    consumer: 'legacy product intel / fit-check routes',
    prompt_source: 'src/auroraBff/routes.js::buildProductDeepScanPrompt(V2/V3/V4)',
    current_version_or_variant: 'v3_default_hardened',
    dormant_variants: ['v2', 'v3_legacy', 'v4', 'strictNarrative_retry', 'escalation_route'],
    provider_path: 'auroraDecisionClient.auroraChat -> upstream Aurora decision service',
    output_contract: {
      schema: 'legacy assessment/evidence/confidence/missing_info JSON',
      schema_required: ['assessment', 'evidence', 'confidence', 'missing_info'],
      consumer_required: ['assessment.summary', 'formula_intent', 'how_to_use', 'reasons', 'watchouts'],
    },
    goal: 'Evaluate a specific product against the user profile with grounded fit, risk, and usage reasoning.',
    deterministic_boundary: ['Normalizer, gap contract, narrative retry, and escalation selection stay deterministic.', 'Prompt owns the structured assessment and evidence pack.'],
    hard_rules: ['Do not guess a brand when the anchor is unresolved.', 'SPF / retinoid / fragrance verification rules must stay conservative.', 'Assessment fields must be non-repetitive and product-level.'],
    missing_data_policy: ['If INCI verification is weak, downgrade verdict level and flag verification needs.', 'If anchor is unresolved, stay category-level rather than brand-specific.'],
    forbidden_behaviors: ['No brand hallucination.', 'No profile-echo filler in formula_intent.', 'No fabricated sources or clinical certainty.'],
    archetype: 'structured analyzer / planner',
    best_prompt_skeleton: ['Role: objective product analyst.', 'Task: deep-scan a product for suitability.', 'Output contract: assessment/evidence/confidence JSON.', 'Hard rules: non-repetition, no brand guessing, conservative verification.'],
    locale_policy: 'English prompt body; upstream can localize later if needed.',
    example_policy: 'One structure-only JSON example plus a no-anchor negative example.',
    current_eval_assets: [
      'tests/aurora_bff_product_intel.test.js',
      'tests/aurora_product_analysis_v4.test.js',
      'tests/aurora_legacy_product_intel_prompt_contract.node.test.cjs',
      'tests/cases_shopping_focus.jsonl',
    ],
    rewrite_priority: 'P0',
  }),
  makeNode({
    node_id: 'legacy.reco.main_selector',
    cluster: 'legacy reco selection',
    runtime_surface: 'legacy recommendation flow',
    call_mode: 'upstream_prompt',
    entrypoint: 'buildAuroraProductRecommendationsQuery',
    consumer: 'legacy reco main route',
    prompt_source: 'src/auroraBff/routes.js::reco_main_v1_0 system + user payload',
    current_version_or_variant: 'reco_main_v1_0_hardened',
    dormant_variants: ['product_relevance_dual_qa_off_default'],
    provider_path: 'auroraDecisionClient.auroraChat -> upstream Aurora decision service',
    output_contract: {
      schema: 'reco_main_v1_0 output_schema',
      schema_required: ['recommendations', 'confidence', 'missing_info', 'warnings'],
      consumer_required: ['sku grounding copied from candidates', 'reasons[]', 'evidence_pack'],
    },
    goal: 'Rank skincare candidates into grounded product picks without inventing SKU facts or exceeding candidate constraints.',
    deterministic_boundary: ['Guardrails, prompt contract verification, and catalog sanitation remain deterministic.', 'Prompt only ranks and justifies candidates.'],
    hard_rules: ['Select only from candidates when provided.', 'Never invent SKU IDs or URLs.', 'If fewer than 5 safe items exist, return fewer.'],
    missing_data_policy: ['Use warnings for missing profile fields.', 'Return empty or short recommendation lists instead of guessy filler.'],
    forbidden_behaviors: ['No checkout links.', 'No clarifying questions.', 'No generic routine dump.'],
    archetype: 'strict selector / ranker',
    best_prompt_skeleton: ['Role: skincare ranking engine.', 'Task: rank supplied candidates into product picks.', 'Output contract: recommendation list JSON.', 'Hard rules: candidate-only grounding and concise reasons.'],
    locale_policy: 'English prompt body; meta.lang in the payload controls downstream language.',
    example_policy: 'Prefer schema and one candidate-grounding counterexample.',
    current_eval_assets: ['tests/aurora_bff.node.test.cjs', 'tests/aurora_bff_reco_catalog.node.test.cjs', 'tests/aurora_legacy_reco_prompt_contract.node.test.cjs', 'scripts/aurora_reco_prod_manual_suite.cjs'],
    rewrite_priority: 'P0',
  }),
  makeNode({
    node_id: 'legacy.reco.alternatives_selector',
    cluster: 'legacy reco selection',
    runtime_surface: 'legacy alternatives / dupe selection',
    call_mode: 'upstream_prompt',
    entrypoint: 'buildAuroraRecoAlternativesQuery',
    consumer: 'legacy reco alternatives flow',
    prompt_source: 'src/auroraBff/routes.js::reco_alternatives_v1_0 system + payload',
    current_version_or_variant: 'reco_alternatives_v1_0_hardened',
    dormant_variants: [],
    provider_path: 'auroraDecisionClient.auroraChat -> upstream Aurora decision service',
    output_contract: {
      schema: 'alternatives selector JSON',
      schema_required: ['alternatives / recommendations'],
      consumer_required: ['candidate ids copied from provided candidates', 'short reasons'],
    },
    goal: 'Pick a small set of grounded alternatives for an anchor product from a supplied candidate list.',
    deterministic_boundary: ['Candidate normalization and quality gates stay deterministic.', 'Prompt only selects from normalized candidates.'],
    hard_rules: ['Select only from context.candidates.', 'Keep reasons short.', 'Do not invent product details.'],
    missing_data_policy: ['If no alternatives are good enough, return fewer items.', 'Do not pad with weak matches.'],
    forbidden_behaviors: ['No fake dupes.', 'No new URLs.', 'No verbose marketing copy.'],
    archetype: 'strict selector / ranker',
    best_prompt_skeleton: ['Role: strict alternatives selector.', 'Task: choose up to N alternatives from candidates.', 'Output contract: alternative list JSON.', 'Hard rules: groundedness and brevity.'],
    locale_policy: 'English prompt body; localized display is a downstream concern.',
    example_policy: 'Schema-only examples are sufficient.',
    current_eval_assets: ['tests/dupe_suggest_p0_regression.test.js', 'tests/aurora_bff_reco_catalog.node.test.cjs', 'tests/aurora_legacy_reco_prompt_contract.node.test.cjs'],
    rewrite_priority: 'P1',
  }),
  makeNode({
    node_id: 'legacy.reco.product_lookup_fallback',
    cluster: 'legacy reco selection',
    runtime_surface: 'legacy purchasable fallback',
    call_mode: 'structured_llm',
    entrypoint: 'buildProductLookupLlmFallbackPrompt -> callGeminiJsonObject',
    consumer: 'recoverProductsWithLlmFallbackFromQueries',
    prompt_source: 'src/auroraBff/routes.js::buildProductLookupLlmFallbackPrompt',
    current_version_or_variant: 'inline_selector_v2',
    dormant_variants: [],
    provider_path: 'callGeminiJsonObject -> Gemini structured JSON',
    output_contract: {
      schema: 'products[] selector JSON',
      schema_required: ['products[]'],
      consumer_required: ['name', 'brand', 'category', 'pdp_url', 'why'],
    },
    goal: 'Recover purchasable skincare products from an allowed candidate set when catalog search is empty or degraded.',
    deterministic_boundary: ['URL allowlists, strict candidate filtering, and fallback reason codes remain deterministic.', 'Prompt only selects allowed products.'],
    hard_rules: ['Use only context.product_candidates.', 'Return direct PDP URLs only.', 'Skincare only.'],
    missing_data_policy: ['If no valid candidate fits, return empty products[] rather than reaching outside context.'],
    forbidden_behaviors: ['No search URLs.', 'No invented products.', 'No non-skincare items.'],
    archetype: 'strict selector / ranker',
    best_prompt_skeleton: ['Role: strict fallback product selector.', 'Task: select purchasable skincare products from candidate context.', 'Output contract: products[].', 'Hard rules: candidate-only URLs and skincare filter.'],
    locale_policy: 'English prompt body only.',
    example_policy: 'One negative example for search URLs is useful.',
    current_eval_assets: [
      'tests/aurora_bff_purchasable_fallback_chain.node.test.cjs',
      'tests/aurora_legacy_purchasable_fallback_prompt_contract.node.test.cjs',
    ],
    rewrite_priority: 'P1',
  }),
  makeNode({
    node_id: 'legacy.ingredient.lookup_upstream',
    cluster: 'legacy ingredient research',
    runtime_surface: 'legacy ingredient lookup route',
    call_mode: 'upstream_prompt',
    entrypoint: 'buildIngredientLookupUpstreamPrompt',
    consumer: 'legacy ingredient lookup upstream call',
    prompt_source: 'src/auroraBff/routes.js::buildIngredientLookupUpstreamPrompt',
    current_version_or_variant: 'inline_lookup_v2',
    dormant_variants: [],
    provider_path: 'auroraDecisionClient.auroraChat -> upstream Aurora decision service',
    output_contract: {
      schema: 'upstream free-form answer',
      schema_required: [],
      consumer_required: ['1-minute ingredient report qualities: benefits, evidence, watchouts, risk by profile'],
    },
    goal: 'Ask the upstream model for a compact ingredient lookup answer when the user wants a quick explanation.',
    deterministic_boundary: ['Routing and follow-up cards stay deterministic.', 'Prompt only shapes the upstream answer request.'],
    hard_rules: ['Keep the report compact.', 'Focus on benefits, evidence, watchouts, risk by profile.', 'No generic shopping pitch.'],
    missing_data_policy: ['If the ingredient is ambiguous, keep the report generic and brief.'],
    forbidden_behaviors: ['No product list dumping.', 'No medical diagnosis.', 'No long essay.'],
    archetype: 'conversational answerer',
    best_prompt_skeleton: ['Role: compact ingredient explainer.', 'Task: request a 1-minute ingredient report.', 'Hard rules: benefits, evidence, watchouts, risk by profile.'],
    locale_policy: 'Prompt is English or Chinese depending on route language.',
    example_policy: 'No examples needed.',
    current_eval_assets: [
      'tests/aurora_bff_ingredient_report_individualization.node.test.cjs',
      'tests/aurora_legacy_ingredient_research_prompt_contract.node.test.cjs',
    ],
    rewrite_priority: 'P2',
  }),
  makeNode({
    node_id: 'legacy.ingredient.reco_upstream',
    cluster: 'legacy reco selection',
    runtime_surface: 'legacy ingredient-constrained recommendations',
    call_mode: 'upstream_prompt',
    entrypoint: 'buildIngredientRecoUpstreamPrompt',
    consumer: 'legacy ingredient recommendation upstream call',
    prompt_source: 'src/auroraBff/routes.js::buildIngredientRecoUpstreamPrompt',
    current_version_or_variant: 'inline_ingredient_reco_v2',
    dormant_variants: [],
    provider_path: 'auroraDecisionClient.auroraChat -> upstream Aurora decision service',
    output_contract: {
      schema: 'upstream product recommendation answer',
      schema_required: [],
      consumer_required: ['ingredient-constrained picks or an explainable empty result'],
    },
    goal: 'Force upstream recommendation generation to respect ingredient constraints instead of falling back to generic skincare picks.',
    deterministic_boundary: ['Candidate filters and entry-source routing are deterministic.', 'Prompt only states the hard ingredient constraints.'],
    hard_rules: ['Select only from product candidates when supplied.', 'If no constrained match exists, explain and return empty.', 'Tie every pick to the ingredient goal.'],
    missing_data_policy: ['If goal or candidates are weak, prefer an empty result over generic recs.'],
    forbidden_behaviors: ['No generic recommendations.', 'No inventing product candidates.', 'No ignoring ingredient context.'],
    archetype: 'strict selector / ranker',
    best_prompt_skeleton: ['Role: ingredient-constrained selector.', 'Task: generate recommendations under hard ingredient constraints.', 'Hard rules: no generic recs and explainable empty state.'],
    locale_policy: 'Prompt localizes by route language when needed.',
    example_policy: 'One negative example for empty constrained results is enough.',
    current_eval_assets: [
      'tests/aurora_bff_ingredient_report_individualization.node.test.cjs',
      'tests/aurora_bff_reco_catalog.node.test.cjs',
      'tests/aurora_legacy_reco_prompt_contract.node.test.cjs',
    ],
    rewrite_priority: 'P2',
  }),
  makeNode({
    node_id: 'legacy.ingredient.research_sync',
    cluster: 'legacy ingredient research',
    runtime_surface: 'legacy ingredient sync research',
    call_mode: 'structured_llm',
    entrypoint: 'buildIngredientResearchPrompts -> callGeminiJsonObject',
    consumer: 'runIngredientResearchSync',
    prompt_source: 'src/auroraBff/routes.js::buildIngredientResearchPrompts',
    current_version_or_variant: 'ingredient_research_v2_lite_hardened',
    dormant_variants: [],
    provider_path: 'callGeminiJsonObject -> Gemini structured JSON',
    output_contract: {
      schema: 'ingredient_research_v2_lite JSON',
      schema_required: ['ingredient', 'overview', 'benefits', 'safety', 'usage', 'confidence', 'evidence'],
      consumer_required: ['citations limited to context.sources', 'top_products optional buckets'],
    },
    goal: 'Produce a compact, evidence-bounded ingredient research packet that can be sanitized into the legacy ingredient research card.',
    deterministic_boundary: ['Sanitizer enforces citation allowlists, unknown handling, and fallback watchouts.', 'Prompt should still return near-schema-complete JSON.'],
    hard_rules: ['Only cite context.sources.', 'Use null/[] instead of "unknown".', 'Stay brief and non-medical.'],
    missing_data_policy: ['If no sources exist, citations must be [].', 'If evidence is weak, set low confidence and limited claims.'],
    forbidden_behaviors: ['No hallucinated citations.', 'No diagnosis or treatment instructions.', 'No bloated prose.'],
    archetype: 'structured analyzer / planner',
    best_prompt_skeleton: ['Role: ingredient research analyst.', 'Task: analyze only the named ingredient.', 'Output contract: v2-lite research JSON.', 'Hard rules: citation allowlist and concise fields.'],
    locale_policy: 'English prompt body; language is passed in context and should control output strings.',
    example_policy: 'Use schema-only examples and a fail-safe short-circuit rule.',
    current_eval_assets: [
      'tests/aurora_bff.node.test.cjs',
      'tests/aurora_bff_ingredient_kb_v2.node.test.cjs',
      'tests/aurora_bff_ingredient_report_individualization.node.test.cjs',
      'tests/aurora_legacy_ingredient_research_prompt_contract.node.test.cjs',
    ],
    rewrite_priority: 'P0',
  }),
  makeNode({
    node_id: 'legacy.analysis_story.generate',
    cluster: 'legacy analysis story generation / review',
    runtime_surface: 'analysis_story_v2',
    call_mode: 'structured_llm',
    entrypoint: 'buildAnalysisStoryGenerationPrompt -> callDualQaProvider',
    consumer: 'generateAnalysisStoryV2JsonWithLlm',
    prompt_source: 'src/auroraBff/routes.js::buildAnalysisStoryGenerationPrompt',
    current_version_or_variant: 'aurora.analysis_story.v2.generate_v2',
    dormant_variants: [],
    provider_path: 'callDualQaProvider -> Gemini single by default; OpenAI optional fallback in QA mode',
    output_contract: {
      schema: 'aurora.analysis_story.v2',
      schema_required: ['schema_version', 'confidence_overall', 'priority_findings', 'am_plan', 'pm_plan', 'ui_card_v1', 'disclaimer_non_medical'],
      consumer_required: ['routine_bridge when routine missing', 'profile-aware AM/PM plan', 'timeline', 'safety_notes'],
    },
    goal: 'Generate a readable, evidence-bounded skincare story card that turns analysis evidence into prioritized actions.',
    deterministic_boundary: ['Local deterministic generation and review still exist as fallback.', 'Prompt must stay within provided evidence and schema.'],
    hard_rules: ['Conclusion first, evidence second, actions third.', 'AM/PM plan must be profile-aware.', 'Include routine_bridge when routine is missing.'],
    missing_data_policy: ['If evidence is sparse, use lower confidence and explicit routine bridge.', 'Do not pad with generic placeholder routines.'],
    forbidden_behaviors: ['No medical diagnosis.', 'No brand-specific recs.', 'No fixed-template AM/PM plan for every user.'],
    archetype: 'structured analyzer / planner',
    best_prompt_skeleton: ['Role: skincare story generator.', 'Task: turn evidence into aurora.analysis_story.v2 JSON.', 'Output contract: schema-complete analysis story.', 'Hard rules: profile-aware plan and non-medical disclaimer.'],
    locale_policy: 'English prompt body; downstream may localize card display later.',
    example_policy: 'Use structure-only schema reference, never copyable content examples.',
    current_eval_assets: [
      'tests/aurora_bff_analysis_story_v2.node.test.cjs',
      'tests/aurora_legacy_analysis_story_prompt_contract.node.test.cjs',
      'scripts/smoke_aurora_bff_runtime.sh',
    ],
    rewrite_priority: 'P0',
  }),
  makeNode({
    node_id: 'legacy.analysis_story.review',
    cluster: 'legacy analysis story generation / review',
    runtime_surface: 'analysis_story_v2',
    call_mode: 'structured_llm',
    entrypoint: 'buildAnalysisStoryReviewPrompt -> callDualQaProvider',
    consumer: 'reviewAnalysisStoryV2JsonWithLlm',
    prompt_source: 'src/auroraBff/routes.js::buildAnalysisStoryReviewPrompt',
    current_version_or_variant: 'aurora.analysis_story.v2.review_v2',
    dormant_variants: [],
    provider_path: 'callDualQaProvider -> Gemini/OpenAI QA reviewer',
    output_contract: {
      schema: 'review JSON with approved, issues, patched_story',
      schema_required: ['approved', 'issues', 'patched_story'],
      consumer_required: ['patched_story stays inside evidence boundaries'],
    },
    goal: 'Review and patch an analysis story so it stays factually consistent, safe, and schema-valid.',
    deterministic_boundary: ['Local reviewAnalysisStoryV2Json revalidates the patched story.', 'Prompt reviewer must not introduce new evidence.'],
    hard_rules: ['patched_story must stay within evidence.', 'Keep disclaimer and routine_bridge rules intact.', 'Return strict JSON only.'],
    missing_data_policy: ['If a safe patch is not possible, reject with issues instead of inventing content.'],
    forbidden_behaviors: ['No new evidence.', 'No extra keys.', 'No stylistic rewrites that change meaning.'],
    archetype: 'reviewer / patcher',
    best_prompt_skeleton: ['Role: strict JSON reviewer.', 'Task: approve or patch a story against evidence.', 'Output contract: approved/issues/patched_story.', 'Hard rules: no new evidence and schema safety.'],
    locale_policy: 'English prompt body; review output stays canonical JSON.',
    example_policy: 'Structure-only examples only.',
    current_eval_assets: [
      'tests/aurora_bff_analysis_story_v2.node.test.cjs',
      'tests/aurora_legacy_analysis_story_prompt_contract.node.test.cjs',
    ],
    rewrite_priority: 'P1',
  }),
];

function getNodeSpecMap() {
  return new Map(NODE_SPECS.map((node) => [node.node_id, node]));
}

function getArchetypeMap() {
  return new Map(ARCHETYPE_LIBRARY.map((entry) => [entry.archetype_id, entry]));
}

module.exports = {
  ARCHETYPE_LIBRARY,
  NODE_SPECS,
  getArchetypeMap,
  getNodeSpecMap,
};
