#!/usr/bin/env python3
"""Split ingredient reference review queue into focused work packets.

This script is read-only. It consumes the JSON output from
build_ingredient_reference_review_queue.py and exports smaller CSV files
organized by the most common curation tasks.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any


WORK_PACKET_RULES = {
    "alias_backfill": {"missing_aliases_common", "missing_alias_quality"},
    "parser_notes_backfill": {"missing_notes_for_parser", "missing_cross_market_notes"},
    "ingredient_family_review": {"ingredient_family_other_review"},
    "status_confidence_review": {"review_status_still_draft", "confidence_medium", "confidence_low"},
}


def normalize_reasons(value: Any) -> list[str]:
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    text = str(value or "").strip()
    if not text:
        return []
    return [part.strip() for part in text.split(";") if part.strip()]


def load_queue(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "priority",
        "priority_score",
        "record_id",
        "canonical_inci_name",
        "canonical_display_name",
        "ingredient_family",
        "review_status",
        "confidence",
        "reasons",
    ]
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            out = dict(row)
            reasons = row.get("reasons") or []
            out["reasons"] = "; ".join(reasons if isinstance(reasons, list) else normalize_reasons(reasons))
            writer.writerow(out)


def filter_rows(rows: list[dict[str, Any]], required_reasons: set[str]) -> list[dict[str, Any]]:
    result = []
    for row in rows:
        reasons = set(normalize_reasons(row.get("reasons")))
        if reasons & required_reasons:
            result.append(row)
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description="Split ingredient review queue into focused work packets.")
    parser.add_argument("--queue-json", required=True, help="Path to queue JSON generated by build_ingredient_reference_review_queue.py")
    parser.add_argument("--out-dir", required=True, help="Directory to write work packet CSV files into")
    args = parser.parse_args()

    queue_path = Path(args.queue_json).expanduser().resolve()
    out_dir = Path(args.out_dir).expanduser().resolve()
    payload = load_queue(queue_path)
    rows = payload.get("all_review_rows") or payload.get("top_review_rows") or []

    summary: dict[str, Any] = {
        "queue_json": str(queue_path),
        "out_dir": str(out_dir),
        "total_rows_in_queue_json": len(rows),
        "packets": {},
    }

    for packet_name, reasons in WORK_PACKET_RULES.items():
        packet_rows = filter_rows(rows, reasons)
        out_csv = out_dir / f"{packet_name}.csv"
        write_csv(out_csv, packet_rows)
        summary["packets"][packet_name] = {
            "row_count": len(packet_rows),
            "csv": str(out_csv),
        }

    print(json.dumps(summary, ensure_ascii=True, indent=2))


if __name__ == "__main__":
    main()
