#!/usr/bin/env bash
set -euo pipefail

skip_preflight=0
if [[ "${1:-}" == "--skip-preflight" ]]; then
  skip_preflight=1
fi

if [[ "$skip_preflight" -ne 1 ]]; then
  bash scripts/test_preflight.sh
fi

bash scripts/run_jest_inband.sh --forceExit --runTestsByPath \
  tests/contracts/toolSchemaParity.test.js \
  tests/lookReplicator/lookReplicator_commerce_invoke.test.js \
  tests/integration/invoke.v2.test.js \
  tests/integration/preview_quote.test.js \
  tests/integration/create_order_quote_id_passthrough.test.js \
  tests/integration/create_order_order_request_wrapper.test.js \
  tests/integration/submit_payment_contract.test.js \
  tests/integration/submit_payment_reliability.test.js \
  tests/integration/confirm_payment_reliability.test.js \
  tests/invoke_external_key_auth.test.js \
  tests/integration/request_after_sales_cancel_routing.test.js \
  tests/integration/invoke.offers.resolve.test.js \
  tests/products/product_resolve_route.test.js \
  tests/products/product_search_proxy_route.test.js \
  tests/integration/invoke.get_product_detail.test.js \
  tests/integration/invoke.pdp_and_group.test.js \
  tests/integration/invoke.resolve_product_candidates.test.js \
  tests/integration/invoke.find_products_cache_browse.test.js \
  tests/integration/invoke.find_products_multi_cache_search.test.js \
  tests/integration/invoke.find_products_multi_eligible_only.test.js \
  tests/integration/invoke.find_products_multi_fallback.test.js \
  tests/integration/invoke.track_product_click.test.js \
  tests/admin.search_diagnostics.test.js \
  tests/admin.catalog_cache_diagnostics.test.js \
  tests/adminAuth.test.js \
  tests/pdpCorePrewarmRuntime.test.js \
  tests/auroraBootstrapAuroraOpsRoutes.test.js \
  tests/auroraIngredientLookupSupportRuntime.test.js \
  tests/auroraIngredientRecoContextRuntime.test.js \
  tests/auroraProductIntelBackfillRuntime.test.js \
  tests/auroraProductIntelCompetitorBackfillRuntime.test.js \
  tests/auroraProductIntelGuardrailRuntime.test.js \
  tests/auroraProductIntelUrlIngredientRuntime.test.js \
  tests/auroraProductIntelSupportRuntime.test.js \
  tests/auroraProductIntelCompetitorCoverageRuntime.test.js \
  tests/auroraProductIntelPolicyRuntime.test.js \
  tests/auroraProductIntelRecoContractRuntime.test.js \
  tests/auroraProductIntelUpstreamRuntime.test.js \
  tests/aurora_registerOpsRoutes.test.js \
  tests/auroraBootstrapRecoRoutes.test.js \
  tests/auroraRecoDogfoodRoutes.test.js \
  tests/auroraRecoBlocksDagFallback.test.js \
  tests/auroraBootstrapIdentityRoutes.test.js \
  tests/auroraBootstrapChatRoutes.test.js \
  tests/auroraBootstrapChatRouteRuntime.test.js \
  tests/auroraBootstrapChatRouteRequestRuntime.test.js \
  tests/auroraBootstrapChatRouteShellRuntime.test.js \
  tests/auroraBootstrapChatCoreRuntime.test.js \
  tests/auroraBootstrapChatPreUpstreamCoordinatorRuntime.test.js \
  tests/auroraBootstrapChatPreludeRuntime.test.js \
  tests/auroraBootstrapChatRecommendationRuntime.test.js \
  tests/auroraBootstrapChatTurnFlowRuntime.test.js \
  tests/auroraBootstrapChatTurnPipelineRuntime.test.js \
  tests/auroraChatRouteSupportRuntime.test.js \
  tests/auroraChatBoundaryPreludeRuntime.test.js \
  tests/auroraChatPreludeCoordinatorRuntime.test.js \
  tests/auroraChatTurnSetupRuntime.test.js \
  tests/auroraChatRouteTurnSetupRuntime.test.js \
  tests/auroraChatRouteRequestShellRuntime.test.js \
  tests/auroraChatRoutesClarificationWiring.test.js \
  tests/auroraChatTurnPipelineRuntime.test.js \
  tests/auroraChatPreUpstreamRuntime.test.js \
  tests/auroraChatLoopBreakerRuntime.test.js \
  tests/auroraChatTravelEnvRuntime.test.js \
  tests/auroraChatConflictRuntime.test.js \
  tests/auroraChatBoundaryRuntime.test.js \
  tests/auroraChatPolicyRuntime.test.js \
  tests/auroraChatAdvisoryRuntime.test.js \
  tests/auroraChatDeliveryRuntime.test.js \
  tests/auroraChatRouteDeliveryShellRuntime.test.js \
  tests/auroraChatFollowupRuntime.test.js \
  tests/auroraChatRecoEntryRuntime.test.js \
  tests/auroraChatRecommendationFlowRuntime.test.js \
  tests/auroraChatRecoPreludeRuntime.test.js \
  tests/auroraChatRecommendationRuntime.test.js \
  tests/auroraChatRecoHandoffRuntime.test.js \
  tests/auroraChatRoutineRecoRuntime.test.js \
  tests/auroraChatRoutineGateRuntime.test.js \
  tests/auroraChatRecoArtifactRuntime.test.js \
  tests/auroraChatRecoResolveRuntime.test.js \
  tests/auroraChatRecoResponseRuntime.test.js \
  tests/auroraChatCatalogAvailabilityRuntime.test.js \
  tests/auroraChatFitCheckRuntime.test.js \
  tests/auroraChatDerivedCardsRuntime.test.js \
  tests/auroraChatUpstreamTurnRuntime.test.js \
  tests/auroraChatUpstreamRequestRuntime.test.js \
  tests/auroraChatUpstreamResponseRuntime.test.js \
  tests/auroraChatUpstreamEnvelopeRuntime.test.js \
  tests/auroraChatDiagnosisGateRuntime.test.js \
  tests/auroraChatSafetyRuntime.test.js \
  tests/auroraChatClarificationRuntime.test.js \
  tests/auroraChatEnvelopeMetaRuntime.test.js \
  tests/auroraChatResponseRuntime.test.js \
  tests/auroraChatIngredientReplayRuntime.test.js \
  tests/auroraChatIngredientPreludeRuntime.test.js \
  tests/auroraChatIngredientRouteRuntime.test.js \
  tests/auroraChatIngredientEntryRuntime.test.js \
  tests/auroraChatIngredientLookupRuntime.test.js \
  tests/auroraChatProfileRuntime.test.js \
  tests/auroraChatProfileContinuationRuntime.test.js \
  tests/auroraChatContextRuntime.test.js \
  tests/auroraChatTurnStateRuntime.test.js \
  tests/auroraClarificationStateHelpers.test.js \
  tests/auroraClarificationRuntime.test.js \
  tests/auroraProfileSessionRuntime.test.js \
  tests/auroraIdentityRoutesRuntime.test.js \
  tests/auroraAuthRoutes.test.js \
  tests/auroraBootstrapProductIntelRoutes.test.js \
  tests/auroraBootstrapPhotoRoutes.test.js \
  tests/auroraSessionBootstrapRoutes.test.js \
  tests/auroraProfileRoutes.test.js \
  tests/auroraChatRoutes.test.js \
  tests/auroraBootstrapRecoSupportRuntime.test.js \
  tests/auroraRouteSupportRuntime.test.js \
  tests/auroraRecoPrelabelSupportRuntime.test.js \
  tests/auroraRecoCatalogSearchSupportRuntime.test.js \
  tests/auroraRecoDogfoodEnvelopeRuntime.test.js \
  tests/auroraSkinAnalysisBackfillRuntime.test.js \
  tests/auroraSkinDeepeningRuntime.test.js \
  tests/auroraPhotoFallbackRuntime.test.js \
  tests/auroraRecoRecommendationRoutes.test.js \
  tests/auroraTrackerRoutes.test.js \
  tests/auroraRoutineOfferRoutes.test.js \
  tests/auroraDupeRoutes.test.js \
  tests/auroraSkinAnalysisRoutes.test.js \
  tests/bootstrapGatewaySupportSurface.test.js \
  tests/bootstrapOptionalRouteOwners.test.js \
  tests/gatewayConfig.test.js \
  tests/createHealthRouteHandler.test.js \
  tests/creatorCatalogAutoSyncRuntime.test.js \
  tests/registerGatewayBaseMiddleware.test.js \
  tests/serverTail.test.js \
  tests/serverStartup.test.js \
  tests/registerGatewaySupportRoutes.test.js \
  tests/registerMerchantOpsRoutes.test.js \
  tests/registerAdminCatalogOpsRoutes.test.js \
  tests/registerAdminDiagnosticsRoutes.test.js \
  tests/registerProductResolveRoute.test.js \
  tests/uiGatewayClient.test.js \
  tests/uiChatLlmClient.test.js \
  tests/uiChatAgent.test.js \
  tests/uiChatRoute.test.js \
  tests/uiChatRuntime.test.js \
  tests/commerce/promotions.test.js \
  tests/commerce/runtimeBridge.test.js \
  tests/commerce/bootstrapCommerceEntrypoints.test.js \
  tests/commerce/createInvokeRequestHandler.test.js \
  tests/commerce/registerCommerceHttpRoutes.test.js \
  tests/commerce/externalInvokeRoute.test.js \
  tests/commerce/externalInvokeAuth.test.js \
  tests/commerce/upstreamRetryRuntime.test.js \
  tests/commerce/invokeAppShell.test.js \
  tests/commerce/invokeRequestContext.test.js \
  tests/commerce/configureInvokeResponseShell.test.js \
  tests/commerce/handleInvokeShortCircuit.test.js \
  tests/commerce/prepareInvokeUpstreamRequest.test.js \
  tests/commerce/runInvokeOperationFlow.test.js \
  tests/commerce/executeInvokeUpstreamFlow.test.js \
  tests/commerce/finalizeInvokeResponseFlow.test.js \
  tests/commerce/buildInvokeErrorResponse.test.js \
  tests/commerce/finalizeInvokeSuccessResponse.test.js \
  tests/commerce/finalizeCheckoutResponse.test.js \
  tests/commerce/offersResolve.test.js \
  tests/commerce/invokeTransport.test.js \
  tests/commerce/invokeSearchPrelude.test.js \
  tests/commerce/invokeSearchExceptionFallback.test.js \
  tests/commerce/searchDiagnosticsHelpers.test.js \
  tests/commerce/searchRouteHealth.test.js \
  tests/commerce/searchTrace.test.js \
  tests/commerce/searchGuards.test.js \
  tests/commerce/creatorCacheDiagnostics.test.js \
  tests/commerce/shopifyCurrencyRuntime.test.js \
  tests/commerce/configuredResolverPolicy.test.js \
  tests/commerce/sellability.test.js \
  tests/commerce/queryHeuristics.test.js \
  tests/commerce/cacheSearchRuntime.test.js \
  tests/commerce/searchDedupe.test.js \
  tests/commerce/bootstrapProxySearchRuntime.test.js \
  tests/commerce/searchQueryParams.test.js \
  tests/commerce/agentProductsListResponse.test.js \
  tests/commerce/searchFallbackRuntime.test.js \
  tests/commerce/searchRelevance.test.js \
  tests/commerce/proxySearchFallbacks.test.js \
  tests/commerce/searchResponseFinalizer.test.js
