// Safe style/variant tags (lowercase)
const SAFE_STYLE_TAGS = new Set([
  'cozy',
  'minimal',
  'minimalist',
  'classic',
  'modern',
  'vintage',
  'retro',
  'street',
  'streetwear',
  'casual',
  'everyday',
  'work',
  'office',
  'smart',
  'preppy',
  'sporty',
  'athleisure',
  'active',
  'outdoor',
  'travel',
  'vacation',
  'party',
  'date',
  'formal',
  'chic',
  'edgy',
  'cute',
  'soft',
  'relaxed',
  'oversized',
  'fitted',
  'slim',
  'loose',
  'layering',
  'warm',
  'lightweight',
  'breathable',
  'summer',
  'winter',
  'spring',
  'fall',
  'neutral',
  'colorful',
  'bold',
  'elevated',
  'premium',
  'luxury',
  'budget',
]);

const BANNED_VARIANT_TOKENS = [
  'clinically',
  'clinical',
  'proven',
  'guarantee',
  'guaranteed',
  'cure',
  'treat',
  'heals',
  'therapeutic',
  'doctor',
  'dermatologist',
  'medical',
  'fda',
  'approved',
  'best',
  'perfect',
  'always',
  'never',
  'ultimate',
  'no.1',
  'number one',
  'top-rated',
  'award',
  'safe for',
  'kid safe',
  'baby safe',
  'non-toxic',
  'antibacterial',
  'antiviral',
  'hypoallergenic',
  'organic',
  '100%',
  'pure',
  'genuine',
  'authentic',
  'certified',
  'verified',
  'waterproof',
  'water resistant',
  'fireproof',
  'bulletproof',
  'uv',
  'spf',
  'free',
  'shipping',
  'sale',
  'deal',
  'discount',
  'limited',
  'today only',
  'best price',
  'ignore',
  'previous instructions',
  'system',
  'developer',
  'prompt',
  'tool',
  'call',
  'execute',
  'override',
];

function hasBannedVariantToken(tagLower) {
  return BANNED_VARIANT_TOKENS.some((t) => tagLower.includes(t));
}

function pickVariantSafe(styleTags = []) {
  for (const raw of styleTags) {
    if (!raw) continue;
    const t = String(raw).trim().toLowerCase();
    if (!t) continue;
    if (!SAFE_STYLE_TAGS.has(t)) continue;
    if (hasBannedVariantToken(t)) continue;
    return t;
  }
  return '';
}

module.exports = {
  SAFE_STYLE_TAGS,
  BANNED_VARIANT_TOKENS,
  hasBannedVariantToken,
  pickVariantSafe,
};
