function createFindProductsInvokeSearchFinalizeRuntime(deps = {}) {
  const {
    prepareInvokeSearchDecisionContext,
    applyInvokeBeautyAuthority,
    finalizeInvokeSuccessResponse,
  } = deps;

  async function finalizeInvokeSearchFlow({
    enriched = null,
    existingMeta = null,
    queryText = '',
    skincareHitDecision = null,
    effectiveObservationOnlyBeautySkincareHitQualityGate = false,
    rawProductsForQualityGate = [],
    crossMerchantCacheRouteDebug = null,
    resolverFirstAttempted = false,
    resolverFirstResult = null,
    responseStatus = null,
    invokeStartedAtMs = 0,
    operation = '',
    findProductsExpansionMeta = null,
    beautyMainlineAuthorityActive = false,
    effectiveIntent = null,
    decisionObserverNodes = [],
    semanticContractMeta = null,
    semanticRewriteResultMeta = null,
    semanticOwnerControlled = false,
    semanticOwnerQueryAttempts = [],
    semanticOwnerDecision = null,
    primarySearchTimeoutMs = null,
    primaryQualityGatePassed = false,
    guidanceDirectSupplementValidHit = false,
    primaryIrrelevant = false,
    primaryMonoculture = false,
    primaryLowQualityNonempty = false,
    semanticRetryApplied = false,
    secondaryFallbackMeta = null,
    secondarySupplementMeta = null,
    skipSecondaryFallback = false,
    normalizedSecondaryFallbackSkipReason = null,
    strictBeautyDirectSearch = false,
    beautyDecisionOwner = null,
    beautySemanticOwner = null,
    semanticOwnerCacheSourceIsolated = false,
    semanticOwnerLastResortCacheApplied = false,
    traceAmbiguityScorePre = null,
    primaryDecisionLocked = false,
    primaryDecisionState = null,
    gatewayRequestId = null,
    traceQueryClass = null,
    traceRewriteGate = null,
    traceAssociationPlan = null,
    traceFlagsSnapshot = null,
    defaultSelectionOwner = 'shopping_agent_beauty_mainline',
    fpmGateTrace = [],
    fpmSkippedGatesDueToBudget = [],
    fpmLatencyGuardApplied = false,
    lowConfidenceFlag = false,
    normalizedLowConfidenceReasons = [],
    semanticOwnerExternalRescueQueriesAttempted = [],
    semanticOwnerCacheSourceIsolationReason = null,
    semanticOwnerLastResortCacheQuery = null,
    gatewayTotalBudgetMs = null,
    metadata = null,
    effectivePayload = null,
    req = null,
    queryParams = null,
    requestedTargetStepFamily = null,
    rawUserQuery = '',
    resolverRejectedReason = null,
    resolverRejectedQueryUsed = null,
  } = {}) {
    const decisionContext = prepareInvokeSearchDecisionContext({
      enriched,
      existingMeta,
      queryText,
      skincareHitDecision,
      effectiveObservationOnlyBeautySkincareHitQualityGate,
      rawProductsForQualityGate,
      crossMerchantCacheRouteDebug,
      shouldAttemptResolverFirst: resolverFirstAttempted,
      resolverFirstResult,
      responseStatus,
      invokeStartedAtMs,
      operation,
      findProductsExpansionMeta,
    });

    let nextEnriched = decisionContext.enriched;
    let nextExistingMeta = decisionContext.existingMeta;

    const beautyAuthorityResult = applyInvokeBeautyAuthority({
      enriched: nextEnriched,
      existingMeta: nextExistingMeta,
      operation,
      invalidHitApplied: decisionContext.invalidHitApplied,
      isStrictEmpty: decisionContext.isStrictEmpty,
      hasClarification: decisionContext.hasClarification,
      beautyMainlineAuthorityActive,
      products: decisionContext.products,
      searchDecision: decisionContext.searchDecision,
      querySource: decisionContext.querySource,
      findProductsExpansionMeta,
      effectiveIntent,
      decisionObserverNodes,
      rawProductsForQualityGate,
      primaryPathUsed: decisionContext.primaryPathUsed,
      semanticContractMeta,
      semanticRewriteResultMeta,
      semanticOwnerControlled,
      semanticOwnerQueryAttempts,
      semanticOwnerDecision,
      primarySearchTimeoutMs,
      primaryQualityGatePassed,
      guidanceDirectSupplementValidHit,
      primaryIrrelevant,
      primaryMonoculture,
      primaryLowQualityNonempty,
      semanticRetryApplied,
      secondaryFallbackMeta,
      secondarySupplementMeta,
      skipSecondaryFallback,
      normalizedSecondaryFallbackSkipReason,
      strictBeautyDirectSearch,
      beautyDecisionOwner,
      beautySemanticOwner,
      semanticOwnerCacheSourceIsolated,
      semanticOwnerLastResortCacheApplied,
    });

    nextEnriched = beautyAuthorityResult.enriched;
    nextExistingMeta = beautyAuthorityResult.existingMeta;

    nextEnriched = await finalizeInvokeSuccessResponse({
      enriched: nextEnriched,
      primaryPathUsed: decisionContext.primaryPathUsed,
      invokeStartedAtMs,
      fallbackTriggered: decisionContext.fallbackTriggered,
      fallbackReason: decisionContext.fallbackReason,
      normalizedDecisionObserverNodes:
        beautyAuthorityResult.normalizedDecisionObserverNodes,
      traceAmbiguityScorePre,
      searchDecision: decisionContext.searchDecision,
      primaryDecisionLocked,
      primaryDecisionState,
      hasClarification: decisionContext.hasClarification,
      routeDegradeFlags: decisionContext.routeDegradeFlags,
      gatewayRequestId,
      queryText,
      expandedQuery: decisionContext.expandedQuery,
      expansionMode: beautyAuthorityResult.expansionMode,
      traceQueryClass,
      traceRewriteGate,
      traceAssociationPlan,
      traceFlagsSnapshot,
      effectiveIntent,
      cacheStage: decisionContext.cacheStage,
      upstreamStage: decisionContext.upstreamStage,
      resolverStage: decisionContext.resolverStage,
      searchStageLedger: beautyAuthorityResult.searchStageLedger,
      finalDecision: beautyAuthorityResult.finalDecision,
      relevanceDebug: beautyAuthorityResult.relevanceDebug,
      isStrictEmpty: decisionContext.isStrictEmpty,
      semanticOwnerDecision,
      defaultSelectionOwner,
      fpmGateTrace,
      fpmSkippedGatesDueToBudget,
      fpmLatencyGuardApplied,
      lowConfidenceFlag: beautyAuthorityResult.lowConfidenceFlag,
      normalizedLowConfidenceReasons:
        beautyAuthorityResult.normalizedLowConfidenceReasons,
      semanticContractMeta,
      semanticRewriteResultMeta,
      semanticOwnerQueryAttempts,
      semanticOwnerExternalRescueQueriesAttempted,
      semanticOwnerCacheSourceIsolated,
      semanticOwnerCacheSourceIsolationReason,
      semanticOwnerLastResortCacheApplied,
      semanticOwnerLastResortCacheQuery,
      findProductsExpansionMeta,
      primarySearchTimeoutMs,
      gatewayTotalBudgetMs,
      blockingGateInfo: decisionContext.blockingGateInfo,
      querySource: decisionContext.querySource,
      resolverRejectedReason,
      resolverRejectedQueryUsed,
      metadata,
      effectivePayload,
      req,
      queryParams,
      requestedTargetStepFamily,
      operation,
      rawUserQuery,
    });

    return {
      enriched: nextEnriched,
      existingMeta: nextExistingMeta,
    };
  }

  return {
    finalizeInvokeSearchFlow,
  };
}

module.exports = {
  createFindProductsInvokeSearchFinalizeRuntime,
};
